<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="9.0.5" />
    <PackageReference Include="MudBlazor" Version="9.3.0" />
    <PackageReference Include="Blazor-ApexCharts" Version="6.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Abstractions\Abstractions.csproj" />
    <ProjectReference Include="..\Client.Infrastructure\Client.Infrastructure.csproj" />
    <ProjectReference Include="..\Domain.Projections\Domain.Projections.csproj" />
    <ProjectReference Include="..\Client.SourceGeneration\Client.SourceGeneration.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Shared\" />
    <Folder Include="Suche\" />
  </ItemGroup>
</Project>
