// <auto-generated/> — erzeugt vom Cqrs.Codegen-Prepass. NICHT von Hand ändern.
// FRAMEWORK-Kopf (stabil) + gescannte Domänen-Commands/Events/Trigger. Siehe JsonContextEmitter.
#nullable enable
using System.Text.Json.Serialization;
using Abstractions;
using Infrastructure.Aggregate;
using Infrastructure.Prozess;
using Infrastructure.Projections;
using Infrastructure.PubSub.Messages;

namespace Infrastructure.Serialization;

/// <summary>
/// STJ-Manifest für den internen Actor-Plane (WIRE): Transport-Hüllen + ALLE Commands/Events (inkl.
/// Transient) + Trigger. Polymorphe Interface-Payloads laufen über die eingebackenen Converter.
/// Signale sind BEWUSST nicht registriert (uniform, vom WireSerializerGenerator selbst serialisiert).
/// Der WireSerializerGenerator koppelt die Menge zur Compile-Zeit (Default.{Typ}).
/// </summary>
[JsonSourceGenerationOptions(
    GenerationMode = JsonSourceGenerationMode.Metadata,
    Converters = new[]
    {
        typeof(IEventJsonConverter),
        typeof(ICommandJsonConverter),
        typeof(CommandModusJsonConverter),
        typeof(IStateChangeSignalJsonConverter),
        typeof(IMessageEnvelopeJsonConverter),
        typeof(PidJsonConverter),
    })]
// ── Framework: Wire-Hüllen (IWireMessage) ──
[JsonSerializable(typeof(CommandEnvelope))]
[JsonSerializable(typeof(CommandResult))]
[JsonSerializable(typeof(Wake))]
[JsonSerializable(typeof(WakeAck))]
[JsonSerializable(typeof(EventEnvelope))]
[JsonSerializable(typeof(SignalEnvelope))]
[JsonSerializable(typeof(Publish))]
[JsonSerializable(typeof(Subscribe))]
[JsonSerializable(typeof(Unsubscribe))]
[JsonSerializable(typeof(Ack))]
[JsonSerializable(typeof(Activate))]
[JsonSerializable(typeof(GetSubscriberCount))]
[JsonSerializable(typeof(SubscriberCountResponse))]
[JsonSerializable(typeof(PipelineAck))]
[JsonSerializable(typeof(ProzessWake))]
// ── Framework: Ergebnis-/Prozess-/Inbox-Events (reisen im Wire) ──
[JsonSerializable(typeof(CommandFailed))]
[JsonSerializable(typeof(ProzessGestartet))]
[JsonSerializable(typeof(ProzessBeendet))]
[JsonSerializable(typeof(SchrittGescheitert))]
[JsonSerializable(typeof(KommandoVerarbeitet))]
[JsonSerializable(typeof(KommandoAbgelehnt))]
// ── Domänen-Commands/Events/Trigger (Domain.*) (gescannt) ──
[JsonSerializable(typeof(global::Domain.Datensatz.DatensatzBereitsEingefroren))]
[JsonSerializable(typeof(global::Domain.Datensatz.DatensatzEingefroren))]
[JsonSerializable(typeof(global::Domain.Datensatz.DatensatzErstellt))]
[JsonSerializable(typeof(global::Domain.Datensatz.DatensatzExistiertBereits))]
[JsonSerializable(typeof(global::Domain.Datensatz.DatensatzLeer))]
[JsonSerializable(typeof(global::Domain.Datensatz.EinfrierenAngefordert))]
[JsonSerializable(typeof(global::Domain.Datensatz.EntfernePaar))]
[JsonSerializable(typeof(global::Domain.Datensatz.ErstelleDatensatz))]
[JsonSerializable(typeof(global::Domain.Datensatz.FriereEin))]
[JsonSerializable(typeof(global::Domain.Datensatz.FuegeRangeHinzu))]
[JsonSerializable(typeof(global::Domain.Datensatz.NimmPaarAuf))]
[JsonSerializable(typeof(global::Domain.Datensatz.NimmRangeAuf))]
[JsonSerializable(typeof(global::Domain.Datensatz.PaarAufgenommen))]
[JsonSerializable(typeof(global::Domain.Datensatz.PaarEntfernt))]
[JsonSerializable(typeof(global::Domain.Datensatz.PaareAufgenommen))]
[JsonSerializable(typeof(global::Domain.Datensatz.RangeAngefordert))]
[JsonSerializable(typeof(global::Domain.Datensatz.RangeLeer))]
[JsonSerializable(typeof(global::Domain.Datensatz.SchliesseEinfrierenAb))]
[JsonSerializable(typeof(global::Domain.Datensatz.SetzeSplit))]
[JsonSerializable(typeof(global::Domain.Datensatz.SplitGesetzt))]
[JsonSerializable(typeof(global::Domain.Datensatz.SplitUngueltig))]
[JsonSerializable(typeof(global::Domain.ImagePair.BildNichtVerfuegbar))]
[JsonSerializable(typeof(global::Domain.ImagePair.BildPaarDurchKiKlassifiziert))]
[JsonSerializable(typeof(global::Domain.ImagePair.BildPaarGelabelt))]
[JsonSerializable(typeof(global::Domain.ImagePair.BildRegionGelabelt))]
[JsonSerializable(typeof(global::Domain.ImagePair.BildVerfuegbar))]
[JsonSerializable(typeof(global::Domain.ImagePair.BildVersionBereitsVerfuegbar))]
[JsonSerializable(typeof(global::Domain.ImagePair.EinzelBildDurchKiKlassifiziert))]
[JsonSerializable(typeof(global::Domain.ImagePair.EinzelBildGelabelt))]
[JsonSerializable(typeof(global::Domain.ImagePair.ErstelleImagePair))]
[JsonSerializable(typeof(global::Domain.ImagePair.ImagePairEingabeUngueltig))]
[JsonSerializable(typeof(global::Domain.ImagePair.ImagePairErstellt))]
[JsonSerializable(typeof(global::Domain.ImagePair.ImagePairExistiertBereits))]
[JsonSerializable(typeof(global::Domain.ImagePair.ImagePairInspiziert))]
[JsonSerializable(typeof(global::Domain.ImagePair.ImagePairKomplett))]
[JsonSerializable(typeof(global::Domain.ImagePair.ImagePairNichtGefunden))]
[JsonSerializable(typeof(global::Domain.ImagePair.KlassifiziereBildPaarDurchKi))]
[JsonSerializable(typeof(global::Domain.ImagePair.KlassifiziereEinzelBildDurchKi))]
[JsonSerializable(typeof(global::Domain.ImagePair.LabelBildPaar))]
[JsonSerializable(typeof(global::Domain.ImagePair.LabelBildRegion))]
[JsonSerializable(typeof(global::Domain.ImagePair.LabelEinzelBild))]
[JsonSerializable(typeof(global::Domain.ImagePair.LabelPhysischesProdukt))]
[JsonSerializable(typeof(global::Domain.ImagePair.MarkiereAlsInspiziert))]
[JsonSerializable(typeof(global::Domain.ImagePair.MeldeBildVerfuegbar))]
[JsonSerializable(typeof(global::Domain.ImagePair.PaarNichtKomplett))]
[JsonSerializable(typeof(global::Domain.ImagePair.PhysischesProduktGelabelt))]
[JsonSerializable(typeof(global::Domain.ImagePair.RegionIndexUngueltig))]
[JsonSerializable(typeof(global::Domain.ImagePair.RegionLabelsUngueltig))]
[JsonSerializable(typeof(global::Domain.Modell.ArchiviereModell))]
[JsonSerializable(typeof(global::Domain.Modell.ModellAktiviert))]
[JsonSerializable(typeof(global::Domain.Modell.ModellArchiviert))]
[JsonSerializable(typeof(global::Domain.Modell.ModellBereitsArchiviert))]
[JsonSerializable(typeof(global::Domain.Modell.ModellExistiertBereits))]
[JsonSerializable(typeof(global::Domain.Modell.ModellNichtGefunden))]
[JsonSerializable(typeof(global::Domain.Modell.ModellRegistriert))]
[JsonSerializable(typeof(global::Domain.Modell.RegistriereModell))]
[JsonSerializable(typeof(global::Domain.Modell.SetzeModellAktiv))]
[JsonSerializable(typeof(global::Domain.Pipeline.Benchmark.BenchPing))]
[JsonSerializable(typeof(global::Domain.Pipeline.ImageProcessing.DateiErkannt))]
[JsonSerializable(typeof(global::Domain.Trainingslauf.BricheTrainingAb))]
[JsonSerializable(typeof(global::Domain.Trainingslauf.MarkiereAlsHaengengeblieben))]
[JsonSerializable(typeof(global::Domain.Trainingslauf.MeldeFortschritt))]
[JsonSerializable(typeof(global::Domain.Trainingslauf.MeldeTrainingAbgeschlossen))]
[JsonSerializable(typeof(global::Domain.Trainingslauf.MeldeTrainingBegonnen))]
[JsonSerializable(typeof(global::Domain.Trainingslauf.MeldeTrainingGescheitert))]
[JsonSerializable(typeof(global::Domain.Trainingslauf.StarteTraining))]
[JsonSerializable(typeof(global::Domain.Trainingslauf.TrainingAbgebrochen))]
[JsonSerializable(typeof(global::Domain.Trainingslauf.TrainingAbgeschlossen))]
[JsonSerializable(typeof(global::Domain.Trainingslauf.TrainingAngefordert))]
[JsonSerializable(typeof(global::Domain.Trainingslauf.TrainingBegonnen))]
[JsonSerializable(typeof(global::Domain.Trainingslauf.TrainingBereitsBeendet))]
[JsonSerializable(typeof(global::Domain.Trainingslauf.TrainingFortschritt))]
[JsonSerializable(typeof(global::Domain.Trainingslauf.TrainingGescheitert))]
[JsonSerializable(typeof(global::Domain.Trainingslauf.TrainingHaengengeblieben))]
[JsonSerializable(typeof(global::Domain.Trainingslauf.TrainingNichtAktiv))]
[JsonSerializable(typeof(global::Domain.Trainingslauf.TrainingslaufExistiertBereits))]
[JsonSerializable(typeof(global::Domain.Trainingslauf.TrainingslaufNichtGefunden))]
public partial class CqrsWireJsonContext : JsonSerializerContext
{
}
