// <auto-generated/> — erzeugt vom Cqrs.Codegen-Prepass. NICHT von Hand ändern.
// FRAMEWORK-Kopf (stabil) + gescannte Domänen-Events. Siehe JsonContextEmitter.
#nullable enable
using System.Text.Json.Serialization;
using Infrastructure.Aggregate;
using Infrastructure.Prozess;

namespace Infrastructure.Serialization;

/// <summary>
/// STJ-Manifest über ALLE persistierbaren Events (Marten-STORAGE). Metadata-Mode: kombinierbar mit
/// Martens JsonSerializerOptions + Resolver-Chain. Der EventJsonGenerator koppelt die Menge zur
/// Compile-Zeit (Default.{Event}).
/// </summary>
[JsonSourceGenerationOptions(GenerationMode = JsonSourceGenerationMode.Metadata)]
// ── Framework: Prozess-intern + Aggregat-Inbox (IEvent → persistiert) ──
[JsonSerializable(typeof(ProzessGestartet))]
[JsonSerializable(typeof(ProzessBeendet))]
[JsonSerializable(typeof(SchrittGescheitert))]
[JsonSerializable(typeof(KommandoVerarbeitet))]
[JsonSerializable(typeof(KommandoAbgelehnt))]
// ── Domänen-Events (Domain.*, persistierbar) (gescannt) ──
[JsonSerializable(typeof(global::Domain.Datensatz.DatensatzEingefroren))]
[JsonSerializable(typeof(global::Domain.Datensatz.DatensatzErstellt))]
[JsonSerializable(typeof(global::Domain.Datensatz.EinfrierenAngefordert))]
[JsonSerializable(typeof(global::Domain.Datensatz.PaarAufgenommen))]
[JsonSerializable(typeof(global::Domain.Datensatz.PaarEntfernt))]
[JsonSerializable(typeof(global::Domain.Datensatz.PaareAufgenommen))]
[JsonSerializable(typeof(global::Domain.Datensatz.RangeAngefordert))]
[JsonSerializable(typeof(global::Domain.Datensatz.SplitGesetzt))]
[JsonSerializable(typeof(global::Domain.ImagePair.BildPaarDurchKiKlassifiziert))]
[JsonSerializable(typeof(global::Domain.ImagePair.BildPaarGelabelt))]
[JsonSerializable(typeof(global::Domain.ImagePair.BildRegionGelabelt))]
[JsonSerializable(typeof(global::Domain.ImagePair.BildVerfuegbar))]
[JsonSerializable(typeof(global::Domain.ImagePair.EinzelBildDurchKiKlassifiziert))]
[JsonSerializable(typeof(global::Domain.ImagePair.EinzelBildGelabelt))]
[JsonSerializable(typeof(global::Domain.ImagePair.ImagePairErstellt))]
[JsonSerializable(typeof(global::Domain.ImagePair.ImagePairInspiziert))]
[JsonSerializable(typeof(global::Domain.ImagePair.ImagePairKomplett))]
[JsonSerializable(typeof(global::Domain.ImagePair.PhysischesProduktGelabelt))]
[JsonSerializable(typeof(global::Domain.Modell.ModellAktiviert))]
[JsonSerializable(typeof(global::Domain.Modell.ModellArchiviert))]
[JsonSerializable(typeof(global::Domain.Modell.ModellRegistriert))]
[JsonSerializable(typeof(global::Domain.Trainingslauf.TrainingAbgebrochen))]
[JsonSerializable(typeof(global::Domain.Trainingslauf.TrainingAbgeschlossen))]
[JsonSerializable(typeof(global::Domain.Trainingslauf.TrainingAngefordert))]
[JsonSerializable(typeof(global::Domain.Trainingslauf.TrainingBegonnen))]
[JsonSerializable(typeof(global::Domain.Trainingslauf.TrainingFortschritt))]
[JsonSerializable(typeof(global::Domain.Trainingslauf.TrainingGescheitert))]
[JsonSerializable(typeof(global::Domain.Trainingslauf.TrainingHaengengeblieben))]
public partial class EventJsonSerializerContext : JsonSerializerContext
{
}
