// In Projekt: Infrastructure.SourceGeneration
// Dateiname: AggregateActorGenerator.cs

using Microsoft.CodeAnalysis;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Infrastructure.SourceGeneration
{
    [Generator]
    public class AggregateActorGenerator : ISourceGenerator
    {
        private const string IStateInterfaceFullName = "Abstractions.IState";

        public void Initialize(GeneratorInitializationContext context)
        {
            // Keine Initialisierung per Syntax Receiver nötig.
        }

        public void Execute(GeneratorExecutionContext context)
        {
            List<INamedTypeSymbol> aggregateSymbols = FindIStateImplementations(context.Compilation);

            if (aggregateSymbols.Count == 0)
            {
                return;
            }

            var sortedAggregateSymbols = aggregateSymbols.OrderBy(s => s.Name).ToList();
            
            string aggregateActorsSource = GenerateAggregateActorsFile(sortedAggregateSymbols);
            string generatedAggregatesSource = GenerateAggregatesRegistrationFile(sortedAggregateSymbols);
            
            context.AddSource("AggregateActors.g.cs", aggregateActorsSource);
            context.AddSource("GeneratedAggregates.g.cs", generatedAggregatesSource);
        }

        private List<INamedTypeSymbol> FindIStateImplementations(Compilation compilation)
        {
            var results = new List<INamedTypeSymbol>();
            INamedTypeSymbol? iStateInterface = compilation.GetTypeByMetadataName(IStateInterfaceFullName);
            
            if (iStateInterface == null)
            {
                return results;
            }

            void FindTypes(INamespaceSymbol namespaceSymbol)
            {
                foreach (var type in namespaceSymbol.GetTypeMembers())
                {
                    if (type.TypeKind == TypeKind.Class && 
                        !type.IsAbstract &&
                        type.AllInterfaces.Contains(iStateInterface, SymbolEqualityComparer.Default))
                    {
                        results.Add(type);
                    }
                }

                foreach (var subNamespace in namespaceSymbol.GetNamespaceMembers())
                {
                    FindTypes(subNamespace);
                }
            }

            FindTypes(compilation.GlobalNamespace);
            return results;
        }

        /// <summary>
        /// Generiert Actor-Klassen.
        /// 
        /// ★ Phase 4: Konstruktor hat jetzt IVersionTracker? als optionalen Parameter.
        ///   Reihenfolge: handlerFactory, eventStore, versionTracker?, publisher?
        /// </summary>
        private string GenerateAggregateActorsFile(List<INamedTypeSymbol> aggregateSymbols)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// Actors verwenden Factory-Pattern für korrekte State-Synchronisation");
            sb.AppendLine("// ★ Phase 4: IVersionTracker? für Redis-basierte Stale Detection");
            sb.AppendLine();
            
            var namespaces = new HashSet<string>();
            foreach (var symbol in aggregateSymbols)
            {
                namespaces.Add(symbol.ContainingNamespace.ToDisplayString());
            }

            sb.AppendLine("using Abstractions;");
            sb.AppendLine("using Infrastructure.PubSub;");
            sb.AppendLine("using Microsoft.Extensions.Logging;");
            foreach (var ns in namespaces.OrderBy(n => n))
            {
                sb.AppendLine($"using {ns};");
            }
            sb.AppendLine();

            sb.AppendLine("namespace Infrastructure.Aggregate.ActorSystem;");
            sb.AppendLine();

            foreach (var symbol in aggregateSymbols)
            {
                string aggregateName = symbol.Name;
                
                sb.AppendLine($"public class {aggregateName}Actor : AggregateActorBase<{aggregateName}>");
                sb.AppendLine("{");
                
                // ★ Konstruktor mit IVersionTracker? vor BrokerPublisher?
                sb.AppendLine($"    public {aggregateName}Actor(");
                sb.AppendLine($"        IAggregateHandlerFactory handlerFactory,");
                sb.AppendLine($"        IEventStoreRepository eventStore,");
                sb.AppendLine($"        IVersionTracker? versionTracker = null,");
                sb.AppendLine($"        BrokerPublisher? publisher = null,");
                sb.AppendLine($"        ILogger<{aggregateName}Actor>? logger = null)");
                sb.AppendLine($"        : base(handlerFactory, eventStore, versionTracker, publisher, logger)");
                sb.AppendLine("    {");
                sb.AppendLine("    }");
                sb.AppendLine("}");
                sb.AppendLine();
            }

            return sb.ToString();
        }

        /// <summary>
        /// Generiert DI-Registrierungen und ClusterKinds.
        /// 
        /// GetAllKinds nutzt actorSystem.DI().PropsFor&lt;T&gt;() –
        /// DI löst IVersionTracker automatisch auf, keine Änderung nötig.
        /// </summary>
        private string GenerateAggregatesRegistrationFile(List<INamedTypeSymbol> aggregateSymbols)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// DI-Registrierung für Aggregate-Actors");
            sb.AppendLine();

            var namespaces = new HashSet<string>();
            foreach (var symbol in aggregateSymbols)
            {
                namespaces.Add(symbol.ContainingNamespace.ToDisplayString());
            }
            
            foreach (var ns in namespaces.OrderBy(n => n))
            {
                sb.AppendLine($"using {ns};");
            }
            sb.AppendLine("using Abstractions;");
            sb.AppendLine("using Infrastructure.PubSub;");
            sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
            sb.AppendLine("using Proto;");
            sb.AppendLine("using Proto.Cluster;");
            sb.AppendLine("using Proto.DependencyInjection;");
            sb.AppendLine("using System;");
            sb.AppendLine();

            sb.AppendLine("namespace Infrastructure.Aggregate.ActorSystem;");
            sb.AppendLine();

            sb.AppendLine("public static class GeneratedAggregates");
            sb.AppendLine("{");

            // RegisterAllAggregateComponents
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Registriert alle Aggregate-Actors im DI-Container.");
            sb.AppendLine("    /// Handler werden NICHT registriert - sie werden on-demand von der Factory erstellt.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static IServiceCollection RegisterAllAggregateComponents(this IServiceCollection services)");
            sb.AppendLine("    {");
            sb.AppendLine("        // Factory als Singleton (wird von allen Actors geteilt)");
            sb.AppendLine("        services.AddSingleton<IAggregateHandlerFactory, AggregateHandlerFactory>();");
            sb.AppendLine();
            
            foreach (var symbol in aggregateSymbols)
            {
                string aggregateName = symbol.Name;
                sb.AppendLine($"        // {aggregateName}Actor - bekommt Factory, EventStore, VersionTracker?, Publisher? via DI");
                sb.AppendLine($"        services.AddTransient<{aggregateName}Actor>();");
            }
            sb.AppendLine();
            sb.AppendLine("        return services;");
            sb.AppendLine("    }");
            sb.AppendLine();
            
            // GetAllKinds – unverändert, DI löst IVersionTracker automatisch auf
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Erstellt ClusterKinds für alle Aggregate-Typen.");
            sb.AppendLine("    /// DI löst IVersionTracker? automatisch auf – keine manuelle Verdrahtung nötig.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static ClusterKind[] GetAllKinds(Proto.ActorSystem actorSystem)");
            sb.AppendLine("    {");

            var kindVarNames = new List<string>();
            foreach (var symbol in aggregateSymbols)
            {
                string aggregateName = symbol.Name;
                string kindVarName = $"{char.ToLowerInvariant(aggregateName[0])}{aggregateName.Substring(1)}Kind";
                kindVarNames.Add(kindVarName);

                sb.AppendLine($"        var {kindVarName} = new ClusterKind(");
                sb.AppendLine($"            nameof({aggregateName}),");
                sb.AppendLine($"            actorSystem.DI().PropsFor<{aggregateName}Actor>()");
                sb.AppendLine("        );");
                sb.AppendLine();
            }
            
            sb.AppendLine($"        return new[] {{ {string.Join(", ", kindVarNames)} }};");
            sb.AppendLine("    }");
            
            sb.AppendLine("}");

            return sb.ToString();
        }
    }
}