using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Abstractions.SourceGeneration;
using Core.SourceGeneration;

namespace Infrastructure.SourceGeneration
{
    [Generator]
    public class DtoMapperSourceGenerator : ISourceGenerator
    {
        /// <summary>
        /// Bekannte Enum-Typnamen — wird in GenerateMapperCode befüllt.
        /// Wird von IsKnownEnumType() für Collection-Element-Erkennung benötigt.
        /// </summary>
        private HashSet<string> _enumTypeNames = new HashSet<string>();
        
        public void Initialize(GeneratorInitializationContext context)
        {
            // Keine Initialisierung nÃƒÆ’Ã‚Â¶tig
        }

        public void Execute(GeneratorExecutionContext context)
        {
            var debugInfo = new List<string>();
            debugInfo.Add($"DtoMapperSourceGenerator lÃƒÆ’Ã‚Â¤uft in Assembly: {context.Compilation.AssemblyName}");
            debugInfo.Add($"Timestamp: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");

            try
            {
                // 1. Nutze den existierenden DomainGraphAnalyzer aus Core.SourceGeneration
                var analyzer = DomainGraphAnalyzer.Create(context.Compilation, useGlobalNamespace: true);
                var graphs = analyzer.AnalyzeMessagePayloads();
                
                // NEU: Query-Typen separat laden
                var queryGraphs = analyzer.AnalyzeTypesImplementing("Abstractions.IQuery");
                var queryResponseGraphs = analyzer.AnalyzeTypesImplementing("Abstractions.IQueryResponse");
                
                // Alle Graphen kombinieren
                var allGraphs = graphs.Concat(queryGraphs).Concat(queryResponseGraphs).ToList();
                
                debugInfo.Add($"Gefundene Type-Graphen: {allGraphs.Count}");

                // 2. Nutze den existierenden TypeAggregator aus Core.SourceGeneration
                var aggregator = new TypeAggregator();
                aggregator.AggregateGraphs(allGraphs);
                
                var objectTypes = aggregator.GetTypesSortedByDepth(DomainType.Object);
                var commandTypes = aggregator.GetTypesSortedByDepth(DomainType.Command);
                var eventTypes = aggregator.GetTypesSortedByDepth(DomainType.Event);
                var queryTypes = aggregator.GetTypesSortedByDepth(DomainType.Query);
                var queryResponseTypes = aggregator.GetTypesSortedByDepth(DomainType.QueryResponse);

                debugInfo.Add($"Commands: {commandTypes.Count}");
                debugInfo.Add($"Events: {eventTypes.Count}");
                debugInfo.Add($"Queries: {queryTypes.Count}");
                debugInfo.Add($"QueryResponses: {queryResponseTypes.Count}");
                debugInfo.Add($"Value Objects: {objectTypes.Count}");

                // 3. Generiere Debug Output
                GenerateDebugOutput(context, debugInfo, objectTypes, commandTypes, eventTypes, queryTypes, queryResponseTypes);

                // 4. Generiere echten Mapper Code
                GenerateMapperCode(context, objectTypes, commandTypes, eventTypes, queryTypes, queryResponseTypes);
            }
            catch (Exception ex)
            {
                debugInfo.Add($"FEHLER: {ex.Message}");
                debugInfo.Add($"StackTrace: {ex.StackTrace}");
                GenerateDebugOutput(context, debugInfo, null, null, null, null, null);
            }
        }

        private void GenerateMapperCode(
            GeneratorExecutionContext context,
            List<TypeAggregationResult> objectTypes,
            List<TypeAggregationResult> commandTypes,
            List<TypeAggregationResult> eventTypes,
            List<TypeAggregationResult> queryTypes,
            List<TypeAggregationResult> queryResponseTypes)
        {
            var sb = new StringBuilder();
            
            // Header
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine($"// Generated at: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Globalization;");
            sb.AppendLine("using System.Linq;");
            sb.AppendLine("using ProtoRepo;");
            sb.AppendLine("using Abstractions;");
            
            // Collect all namespaces
            var namespaces = new HashSet<string>();
            var allTypes = objectTypes
                .Concat(commandTypes)
                .Concat(eventTypes)
                .Concat(queryTypes ?? Enumerable.Empty<TypeAggregationResult>())
                .Concat(queryResponseTypes ?? Enumerable.Empty<TypeAggregationResult>());
                
            foreach (var type in allTypes)
            {
                var ns = GetNamespace(type.Node.FullName);
                if (!string.IsNullOrEmpty(ns) && ns != "System" && ns != "ProtoRepo" && ns != "Abstractions")
                    namespaces.Add(ns);
            }
            
            foreach (var ns in namespaces.OrderBy(n => n))
            {
                sb.AppendLine($"using {ns};");
            }
            
            sb.AppendLine();
            sb.AppendLine("namespace Infrastructure.Mappers");
            sb.AppendLine("{");
            
            // Build type lookup for determining helper classes
            var typeLookup = BuildTypeLookup(objectTypes, commandTypes, eventTypes, queryTypes, queryResponseTypes);
            
            // Enum-Typnamen sammeln für Collection-Element-Erkennung
            _enumTypeNames = new HashSet<string>();
            foreach (var obj in objectTypes.Where(t => t.Node.IsEnum))
            {
                _enumTypeNames.Add(GetSimpleTypeName(obj.Node.FullName));
                _enumTypeNames.Add(obj.Node.FullName);
            }
            
            // 1. Partial class ProtoMessageMapper
            GeneratePartialMapperClass(sb);
            
            // 2. Static Helper Classes
            GenerateValueObjectHelpers(sb, objectTypes, typeLookup);
            GenerateCommandHelpers(sb, commandTypes, objectTypes, typeLookup);
            GenerateEventHelpers(sb, eventTypes, objectTypes, typeLookup);
            
            // 3. Query Helpers (NEU)
            if (queryTypes != null && queryTypes.Any())
            {
                GenerateQueryHelpers(sb, queryTypes, objectTypes, typeLookup);
            }
            
            if (queryResponseTypes != null && queryResponseTypes.Any())
            {
                GenerateQueryResponseHelpers(sb, queryResponseTypes, objectTypes, typeLookup);
            }
            
            sb.AppendLine("}");
            
            context.AddSource("ProtoMessageMapper.Generated.cs", sb.ToString());
        }

        private void GeneratePartialMapperClass(StringBuilder sb)
        {
            sb.AppendLine("    public partial class ProtoMessageMapper");
            sb.AppendLine("    {");
            sb.AppendLine("        // Partial class - erweitert die handgeschriebene Implementierung");
            sb.AppendLine("        // Die eigentliche Mapping-Logik ist in den statischen Helper-Klassen");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        private void GenerateValueObjectHelpers(StringBuilder sb, List<TypeAggregationResult> objectTypes, Dictionary<string, DomainType> typeLookup)
        {
            // Filtere primitive, nullable Typen, nullable Domain-Typen und Enums heraus
            // - Primitive Typen brauchen keine Mapper
            // - Nullable Domain-Typen (z.B. Klassifikation?) nutzen den Mapper des Base-Typs
            // - Enums werden via Cast gemappt
            var filteredTypes = objectTypes
                .Where(t => !IsPrimitiveOrNullableType(t.Node.FullName) 
                         && !IsNullableDomainType(t.Node.FullName)
                         && !t.Node.IsEnum)
                .ToList();
            
            if (!filteredTypes.Any()) return;
            
            sb.AppendLine("    internal static class ProtoValueObjectHelpers");
            sb.AppendLine("    {");
            
            foreach (var objType in filteredTypes)
            {
                var typeName = GetSimpleTypeName(objType.Node.FullName);
                var sanitizedTypeName = NameSanitizer.SanitizeName(typeName);
                var dtoName = sanitizedTypeName + "Dto";
                
                // MapToDomain method
                sb.AppendLine($"        public static {typeName} Map{sanitizedTypeName}({dtoName} dto)");
                sb.AppendLine("        {");
                sb.AppendLine("            if (dto == null) return null;");
                sb.AppendLine($"            return new {typeName}(");
                
                var parameters = objType.Node.ConstructorParameters;
                for (int i = 0; i < parameters.Count; i++)
                {
                    var param = parameters[i];
                    var mapping = GenerateParameterMapping(param, "dto", typeLookup);
                    sb.Append($"                {mapping}");
                    if (i < parameters.Count - 1) sb.AppendLine(",");
                    else sb.AppendLine();
                }
                
                sb.AppendLine("            );");
                sb.AppendLine("        }");
                sb.AppendLine();
                
                // MapToDto method - handle collections (RepeatedField in Protobuf)
                var collectionParams = parameters.Where(p => p.IsCollection).ToList();
                var nonCollectionParams = parameters.Where(p => !p.IsCollection).ToList();
                
                sb.AppendLine($"        public static {dtoName} MapToDto({typeName} obj)");
                sb.AppendLine("        {");
                sb.AppendLine("            if (obj == null) return null;");
                
                if (collectionParams.Any())
                {
                    // Has collections - need to use AddRange() for RepeatedField
                    sb.AppendLine($"            var dto = new {dtoName}");
                    sb.AppendLine("            {");
                    
                    foreach (var param in nonCollectionParams)
                    {
                        var propName = ToPascalCase(param.Name);
                        var mapping = GeneratePropertyMapping(param, "obj", propName, typeLookup);
                        sb.AppendLine($"                {propName} = {mapping},");
                    }
                    
                    sb.AppendLine("            };");
                    sb.AppendLine();
                    
                    // Add collections using AddRange
                    foreach (var param in collectionParams)
                    {
                        var propName = ToPascalCase(param.Name);
                        var addRangeMapping = GenerateCollectionAddRangeMapping(param, "obj", propName, typeLookup);
                        sb.AppendLine($"            {addRangeMapping}");
                    }
                    
                    sb.AppendLine();
                    sb.AppendLine("            return dto;");
                }
                else
                {
                    // No collections - simple object initializer
                    sb.AppendLine($"            return new {dtoName}");
                    sb.AppendLine("            {");
                    
                    foreach (var param in parameters)
                    {
                        var propName = ToPascalCase(param.Name);
                        var mapping = GeneratePropertyMapping(param, "obj", propName, typeLookup);
                        sb.AppendLine($"                {propName} = {mapping},");
                    }
                    
                    sb.AppendLine("            };");
                }
                
                sb.AppendLine("        }");
                sb.AppendLine();
            }
            
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        private void GenerateCommandHelpers(StringBuilder sb, List<TypeAggregationResult> commandTypes, List<TypeAggregationResult> objectTypes, Dictionary<string, DomainType> typeLookup)
        {
            if (!commandTypes.Any()) return;
            
            sb.AppendLine("    internal static class ProtoCommandMappingHelpers");
            sb.AppendLine("    {");
            
            // Generate lookup dictionaries
            GenerateLookupDictionaries(sb, commandTypes, "Command", "CommandEnvelopeDto");
            
            // MapToDomain for envelope
            sb.AppendLine("        public static CommandEnvelope MapToDomain(CommandEnvelopeDto dto)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (!CommandMappers.TryGetValue(dto.PayloadCase, out var mapper))");
            sb.AppendLine("                throw new NotSupportedException($\"Unknown command type: {dto.PayloadCase}\");");
            sb.AppendLine();
            sb.AppendLine("            var payload = mapper(dto);");
            sb.AppendLine();
            sb.AppendLine("            return new CommandEnvelope");
            sb.AppendLine("            {");
            sb.AppendLine("                CommandId = Guid.Parse(dto.CommandId),");
            sb.AppendLine("                AggregateId = Guid.Parse(dto.AggregateId),");
            sb.AppendLine("                AggregateType = dto.AggregateType,");
            sb.AppendLine("                ExpectedVersion = dto.ExpectedVersion,");
            sb.AppendLine("                CreatedAtUtc = DateTimeOffset.FromUnixTimeMilliseconds(dto.CreatedAtUtc),");
            sb.AppendLine("                CorrelationId = dto.CorrelationId,");
            sb.AppendLine("                UserId = dto.UserId,");
            sb.AppendLine("                OriginSessionId = string.IsNullOrEmpty(dto.OriginSessionId) ? null : dto.OriginSessionId,");
            sb.AppendLine("                Payload = payload");
            sb.AppendLine("            };");
            sb.AppendLine("        }");
            sb.AppendLine();
            
            // MapToDto for envelope
            sb.AppendLine("        public static CommandEnvelopeDto MapToDto(CommandEnvelope envelope)");
            sb.AppendLine("        {");
            sb.AppendLine("            var dto = new CommandEnvelopeDto");
            sb.AppendLine("            {");
            sb.AppendLine("                CommandId = envelope.CommandId.ToString(),");
            sb.AppendLine("                AggregateId = envelope.AggregateId.ToString(),");
            sb.AppendLine("                AggregateType = envelope.AggregateType ?? string.Empty,");
            sb.AppendLine("                ExpectedVersion = envelope.ExpectedVersion,");
            sb.AppendLine("                CreatedAtUtc = envelope.CreatedAtUtc.ToUnixTimeMilliseconds(),");
            sb.AppendLine("                CorrelationId = envelope.CorrelationId,");
            sb.AppendLine("                UserId = envelope.UserId,");
            sb.AppendLine("                OriginSessionId = envelope.OriginSessionId ?? string.Empty");
            sb.AppendLine("            };");
            sb.AppendLine();
            sb.AppendLine("            if (!CommandReverseMappers.TryGetValue(envelope.Payload.GetType(), out var mapper))");
            sb.AppendLine("                throw new NotSupportedException($\"Unknown command type: {envelope.Payload.GetType().Name}\");");
            sb.AppendLine();
            sb.AppendLine("            mapper(envelope.Payload, dto);");
            sb.AppendLine("            return dto;");
            sb.AppendLine("        }");
            sb.AppendLine();
            
            // Individual mappers
            GenerateIndividualMappers(sb, commandTypes, objectTypes, "Command", typeLookup);
            
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        private void GenerateEventHelpers(StringBuilder sb, List<TypeAggregationResult> eventTypes, List<TypeAggregationResult> objectTypes, Dictionary<string, DomainType> typeLookup)
        {
            if (!eventTypes.Any()) return;
            
            sb.AppendLine("    internal static class ProtoEventMappingHelpers");
            sb.AppendLine("    {");
            
            // Generate lookup dictionaries
            GenerateLookupDictionaries(sb, eventTypes, "Event", "EventEnvelopeDto");
            
            // MapToDomain for envelope
            sb.AppendLine("        public static EventEnvelope MapToDomain(EventEnvelopeDto dto)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (!EventMappers.TryGetValue(dto.PayloadCase, out var mapper))");
            sb.AppendLine("                throw new NotSupportedException($\"Unknown event type: {dto.PayloadCase}\");");
            sb.AppendLine();
            sb.AppendLine("            var payload = mapper(dto);");
            sb.AppendLine();
            sb.AppendLine("            return new EventEnvelope");
            sb.AppendLine("            {");
            sb.AppendLine("                EventId = Guid.Parse(dto.EventId),");
            sb.AppendLine("                AggregateId = Guid.Parse(dto.AggregateId),");
            sb.AppendLine("                AggregateType = dto.AggregateType,");
            sb.AppendLine("                AggregateVersion = dto.AggregateVersion,");
            sb.AppendLine("                CreatedAtUtc = DateTimeOffset.FromUnixTimeMilliseconds(dto.CreatedAtUtc),");
            sb.AppendLine("                CausationId = dto.CausationId,");
            sb.AppendLine("                CorrelationId = dto.CorrelationId,");
            sb.AppendLine("                UserId = dto.UserId,");
            sb.AppendLine("                TargetSubscriberId = string.IsNullOrEmpty(dto.TargetSubscriberId) ? null : dto.TargetSubscriberId,");
            sb.AppendLine("                Payload = payload");
            sb.AppendLine("            };");
            sb.AppendLine("        }");
            sb.AppendLine();
            
            // MapToDto for envelope
            sb.AppendLine("        public static EventEnvelopeDto MapToDto(EventEnvelope envelope)");
            sb.AppendLine("        {");
            sb.AppendLine("            var dto = new EventEnvelopeDto");
            sb.AppendLine("            {");
            sb.AppendLine("                EventId = envelope.EventId.ToString(),");
            sb.AppendLine("                AggregateId = envelope.AggregateId.ToString(),");
            sb.AppendLine("                AggregateType = envelope.AggregateType ?? string.Empty,");
            sb.AppendLine("                AggregateVersion = envelope.AggregateVersion,");
            sb.AppendLine("                CreatedAtUtc = envelope.CreatedAtUtc.ToUnixTimeMilliseconds(),");
            sb.AppendLine("                CausationId = envelope.CausationId,");
            sb.AppendLine("                CorrelationId = envelope.CorrelationId,");
            sb.AppendLine("                UserId = envelope.UserId,");
            sb.AppendLine("                TargetSubscriberId = envelope.TargetSubscriberId ?? string.Empty");
            sb.AppendLine("            };");
            sb.AppendLine();
            sb.AppendLine("            if (!EventReverseMappers.TryGetValue(envelope.Payload.GetType(), out var mapper))");
            sb.AppendLine("                throw new NotSupportedException($\"Unknown event type: {envelope.Payload.GetType().Name}\");");
            sb.AppendLine();
            sb.AppendLine("            mapper(envelope.Payload, dto);");
            sb.AppendLine("            return dto;");
            sb.AppendLine("        }");
            sb.AppendLine();
            
            // Individual mappers
            GenerateIndividualMappers(sb, eventTypes, objectTypes, "Event", typeLookup);
            
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        private void GenerateQueryHelpers(StringBuilder sb, List<TypeAggregationResult> queryTypes, List<TypeAggregationResult> objectTypes, Dictionary<string, DomainType> typeLookup)
        {
            if (!queryTypes.Any()) return;
            
            sb.AppendLine("    internal static class ProtoQueryMappingHelpers");
            sb.AppendLine("    {");
            
            // Generate lookup dictionaries
            GenerateLookupDictionaries(sb, queryTypes, "Query", "QueryPayloadDto");
            
            // MapToDomain
            sb.AppendLine("        public static IQuery MapToDomain(QueryPayloadDto dto)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (!QueryMappers.TryGetValue(dto.PayloadCase, out var mapper))");
            sb.AppendLine("                throw new NotSupportedException($\"Unknown query type: {dto.PayloadCase}\");");
            sb.AppendLine();
            sb.AppendLine("            return mapper(dto);");
            sb.AppendLine("        }");
            sb.AppendLine();
            
            // MapToDto
            sb.AppendLine("        public static QueryPayloadDto MapToDto(IQuery query)");
            sb.AppendLine("        {");
            sb.AppendLine("            var dto = new QueryPayloadDto();");
            sb.AppendLine();
            sb.AppendLine("            if (!QueryReverseMappers.TryGetValue(query.GetType(), out var mapper))");
            sb.AppendLine("                throw new NotSupportedException($\"Unknown query type: {query.GetType().Name}\");");
            sb.AppendLine();
            sb.AppendLine("            mapper(query, dto);");
            sb.AppendLine("            return dto;");
            sb.AppendLine("        }");
            sb.AppendLine();
            
            // Individual mappers
            GenerateIndividualMappers(sb, queryTypes, objectTypes, "Query", typeLookup);
            
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        private void GenerateQueryResponseHelpers(StringBuilder sb, List<TypeAggregationResult> responseTypes, List<TypeAggregationResult> objectTypes, Dictionary<string, DomainType> typeLookup)
        {
            if (!responseTypes.Any()) return;
            
            sb.AppendLine("    internal static class ProtoQueryResponseMappingHelpers");
            sb.AppendLine("    {");
            
            // Generate lookup dictionaries
            GenerateLookupDictionaries(sb, responseTypes, "QueryResponse", "QueryResponsePayloadDto");
            
            // MapToDomain
            sb.AppendLine("        public static IQueryResponse MapToDomain(QueryResponsePayloadDto dto)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (!QueryResponseMappers.TryGetValue(dto.PayloadCase, out var mapper))");
            sb.AppendLine("                throw new NotSupportedException($\"Unknown query response type: {dto.PayloadCase}\");");
            sb.AppendLine();
            sb.AppendLine("            return mapper(dto);");
            sb.AppendLine("        }");
            sb.AppendLine();
            
            // MapToDto
            sb.AppendLine("        public static QueryResponsePayloadDto MapToDto(IQueryResponse response)");
            sb.AppendLine("        {");
            sb.AppendLine("            var dto = new QueryResponsePayloadDto();");
            sb.AppendLine();
            sb.AppendLine("            if (!QueryResponseReverseMappers.TryGetValue(response.GetType(), out var mapper))");
            sb.AppendLine("                throw new NotSupportedException($\"Unknown query response type: {response.GetType().Name}\");");
            sb.AppendLine();
            sb.AppendLine("            mapper(response, dto);");
            sb.AppendLine("            return dto;");
            sb.AppendLine("        }");
            sb.AppendLine();
            
            // Individual mappers
            GenerateIndividualMappers(sb, responseTypes, objectTypes, "QueryResponse", typeLookup);
            
            sb.AppendLine("    }");
        }

        private void GenerateLookupDictionaries(StringBuilder sb, List<TypeAggregationResult> types, string typeName, string envelopeDtoName)
        {
            // Interface-Name ableiten
            var interfaceName = typeName switch
            {
                "Command" => "ICommand",
                "Event" => "IEvent",
                "Query" => "IQuery",
                "QueryResponse" => "IQueryResponse",
                _ => $"I{typeName}"
            };
            
            // Forward mapping dictionary
            sb.AppendLine($"        private static readonly Dictionary<{envelopeDtoName}.PayloadOneofCase, Func<{envelopeDtoName}, {interfaceName}>> {typeName}Mappers =");
            sb.AppendLine($"            new Dictionary<{envelopeDtoName}.PayloadOneofCase, Func<{envelopeDtoName}, {interfaceName}>>");
            sb.AppendLine("            {");
            
            foreach (var type in types)
            {
                var simpleName = GetSimpleTypeName(type.Node.FullName);
                var sanitizedName = NameSanitizer.SanitizeName(simpleName);
                var fieldName = NameSanitizer.ToPascalCase(NameSanitizer.ToSnakeCase(simpleName));
                sb.AppendLine($"                [{envelopeDtoName}.PayloadOneofCase.{fieldName}] = dto => Map{sanitizedName}(dto.{fieldName}),");
            }
            
            sb.AppendLine("            };");
            sb.AppendLine();
            
            // Reverse mapping dictionary
            sb.AppendLine($"        private static readonly Dictionary<Type, Action<{interfaceName}, {envelopeDtoName}>> {typeName}ReverseMappers =");
            sb.AppendLine($"            new Dictionary<Type, Action<{interfaceName}, {envelopeDtoName}>>");
            sb.AppendLine("            {");
            
            foreach (var type in types)
            {
                var simpleName = GetSimpleTypeName(type.Node.FullName);
                var fieldName = NameSanitizer.ToPascalCase(NameSanitizer.ToSnakeCase(simpleName));
                sb.AppendLine($"                [typeof({simpleName})] = (payload, dto) => dto.{fieldName} = MapToDto(({simpleName})payload),");
            }
            
            sb.AppendLine("            };");
            sb.AppendLine();
        }

        private void GenerateIndividualMappers(StringBuilder sb, List<TypeAggregationResult> types, List<TypeAggregationResult> objectTypes, string typeName, Dictionary<string, DomainType> typeLookup = null)
        {
            foreach (var type in types)
            {
                var simpleName = GetSimpleTypeName(type.Node.FullName);
                var sanitizedName = NameSanitizer.SanitizeName(simpleName);
                var dtoName = sanitizedName + "Dto";
                
                // MapToDomain
                sb.AppendLine($"        private static {simpleName} Map{sanitizedName}({dtoName} dto)");
                sb.AppendLine("        {");
                
                var parameters = type.Node.ConstructorParameters;
                if (parameters.Count == 0)
                {
                    // Parameterloser Konstruktor
                    sb.AppendLine($"            return new {simpleName}();");
                }
                else
                {
                    sb.AppendLine($"            return new {simpleName}(");
                    
                    for (int i = 0; i < parameters.Count; i++)
                    {
                        var param = parameters[i];
                        var mapping = GenerateParameterMapping(param, "dto", typeLookup);
                        sb.Append($"                {mapping}");
                        if (i < parameters.Count - 1) sb.AppendLine(",");
                        else sb.AppendLine();
                    }
                    
                    sb.AppendLine("            );");
                }
                sb.AppendLine("        }");
                sb.AppendLine();
                
                // MapToDto - separate handling for collections (RepeatedField in Protobuf)
                var collectionParams = parameters.Where(p => p.IsCollection).ToList();
                var nonCollectionParams = parameters.Where(p => !p.IsCollection).ToList();
                
                sb.AppendLine($"        private static {dtoName} MapToDto({simpleName} obj)");
                sb.AppendLine("        {");
                
                if (collectionParams.Any())
                {
                    // Has collections - need to use AddRange() for RepeatedField
                    sb.AppendLine($"            var dto = new {dtoName}");
                    sb.AppendLine("            {");
                    
                    foreach (var param in nonCollectionParams)
                    {
                        var propName = ToPascalCase(param.Name);
                        var mapping = GeneratePropertyMapping(param, "obj", propName, typeLookup);
                        sb.AppendLine($"                {propName} = {mapping},");
                    }
                    
                    sb.AppendLine("            };");
                    sb.AppendLine();
                    
                    // Add collections using AddRange
                    foreach (var param in collectionParams)
                    {
                        var propName = ToPascalCase(param.Name);
                        var addRangeMapping = GenerateCollectionAddRangeMapping(param, "obj", propName, typeLookup);
                        sb.AppendLine($"            {addRangeMapping}");
                    }
                    
                    sb.AppendLine();
                    sb.AppendLine("            return dto;");
                }
                else
                {
                    // No collections - simple object initializer
                    sb.AppendLine($"            return new {dtoName}");
                    sb.AppendLine("            {");
                    
                    foreach (var param in parameters)
                    {
                        var propName = ToPascalCase(param.Name);
                        var mapping = GeneratePropertyMapping(param, "obj", propName, typeLookup);
                        sb.AppendLine($"                {propName} = {mapping},");
                    }
                    
                    sb.AppendLine("            };");
                }
                
                sb.AppendLine("        }");
                sb.AppendLine();
            }
        }
        
        /// <summary>
        /// Generates AddRange call for collection properties (Protobuf RepeatedField).
        /// </summary>
        private string GenerateCollectionAddRangeMapping(TypeNode param, string sourceVar, string propName, Dictionary<string, DomainType> typeLookup)
        {
            var elementType = param.CollectionElementType;
            
            // Collection von nullable Enums (z.B. IReadOnlyList<Klassifikation?>)
            // In Proto als repeated string → Enum?.ToString(), null → leerer String
            if (IsNullableEnumType(elementType))
            {
                return $"if ({sourceVar}.{propName} != null) dto.{propName}.AddRange({sourceVar}.{propName}.Select(x => x?.ToString() ?? string.Empty));";
            }
            
            // Collection von non-nullable Enums (z.B. IReadOnlyList<Klassifikation>)
            // In Proto als repeated int32 → (int)enum
            if (IsKnownEnumType(elementType))
            {
                return $"if ({sourceVar}.{propName} != null) dto.{propName}.AddRange({sourceVar}.{propName}.Select(x => (int)x));";
            }
            
            if (TypeMappingHelper.IsProtoScalarType(elementType))
            {
                return $"if ({sourceVar}.{propName} != null) dto.{propName}.AddRange({sourceVar}.{propName});";
            }
            else
            {
                var elementTypeName = GetSimpleTypeName(elementType);
                
                // Determine correct helper class based on element's DomainType
                var elementDomainType = typeLookup != null ? GetDomainTypeForTypeName(elementTypeName, typeLookup) : DomainType.Object;
                var helperClass = GetHelperClassName(elementDomainType);
                
                return $"if ({sourceVar}.{propName} != null) dto.{propName}.AddRange({sourceVar}.{propName}.Select(x => {helperClass}.MapToDto(x)));";
            }
        }

        private string GenerateParameterMapping(TypeNode param, string sourceVar, Dictionary<string, DomainType> typeLookup = null)
        {
            var fieldName = ToPascalCase(param.Name);
            
            // Enum-Handling — unterscheide zwischen nullable und non-nullable
            if (param.IsEnum)
            {
                var typeName = GetSimpleTypeName(param.FullName);
                var sanitizedTypeName = NameSanitizer.SanitizeName(typeName);
                
                // Nullable Enum (z.B. Klassifikation?) - in Proto als string dargestellt
                if (param.FullName.EndsWith("?"))
                {
                    // Proto string → C# Nullable Enum
                    // Leerer String = null, sonst Enum.Parse
                    var baseEnumType = sanitizedTypeName; // ohne ?
                    return $"string.IsNullOrEmpty({sourceVar}.{fieldName}) ? ({baseEnumType}?)null : Enum.Parse<{baseEnumType}>({sourceVar}.{fieldName})";
                }
                else
                {
                    // Non-nullable Enum - in Proto als int32 dargestellt
                    // Proto int32 → C# Enum via Cast
                    return $"({sanitizedTypeName}){sourceVar}.{fieldName}";
                }
            }
            
            // Handle Guid specially
            if (param.FullName == "System.Guid")
                return $"Guid.Parse({sourceVar}.{fieldName})";
            
            // Handle decimal (von string zu decimal)
            if (param.FullName == "decimal" || param.FullName == "System.Decimal")
                return $"decimal.Parse({sourceVar}.{fieldName}, CultureInfo.InvariantCulture)";
            
            // Handle DateTime (von int64 zu DateTimeOffset) — non-nullable
            if (param.FullName == "System.DateTime" || param.FullName == "System.DateTimeOffset")
                return $"DateTimeOffset.FromUnixTimeMilliseconds({sourceVar}.{fieldName})";
            
            // NEU: Handle nullable DateTime/DateTimeOffset (int64 → DateTimeOffset?, 0 = null)
            if (IsNullableDateTimeType(param.FullName))
                return $"{sourceVar}.{fieldName} == 0 ? (DateTimeOffset?)null : DateTimeOffset.FromUnixTimeMilliseconds({sourceVar}.{fieldName})";
            
            // WICHTIG: Prüfe zuerst auf primitive/nullable Typen BEVOR complex type check
            if (IsPrimitiveOrNullableType(param.FullName))
            {
                // Nullable string? -> direkt verwenden, aber leere Strings zu null konvertieren
                if (param.FullName == "string?" || param.FullName == "System.String?")
                    return $"string.IsNullOrEmpty({sourceVar}.{fieldName}) ? null : {sourceVar}.{fieldName}";
                
                // ★ FIX: int32 → Nullable bool? (0=null, 1=true, 2=false)
                // Gegenstück zur Kodierung in GeneratePropertyMapping.
                if (param.FullName == "bool?" || param.FullName == "System.Boolean?")
                    return $"{sourceVar}.{fieldName} switch {{ 1 => (bool?)true, 2 => (bool?)false, _ => null }}";
                
                // Nullable int? -> Proto int32 hat keinen null-Zustand, 0 = null
                if (param.FullName == "int?" || param.FullName == "System.Int32?")
                    return $"{sourceVar}.{fieldName} == 0 ? (int?)null : {sourceVar}.{fieldName}";
                    
                // Andere Skalartypen direkt verwenden
                return $"{sourceVar}.{fieldName}";
            }
            
            // NEU: Handle nullable Domain-Typen (z.B. Klassifikation?)
            // Diese nutzen den Mapper des Base-Typs
            if (IsNullableDomainType(param.FullName))
            {
                var baseTypeName = GetNullableBaseType(param.FullName);
                var simpleBaseType = GetSimpleTypeName(baseTypeName);
                var sanitizedBaseType = NameSanitizer.SanitizeName(simpleBaseType);
                
                // Determine correct helper class based on DomainType
                var domainType = typeLookup != null ? GetDomainTypeForTypeName(simpleBaseType, typeLookup) : DomainType.Object;
                var helperClass = GetHelperClassName(domainType);
                
                return $"{helperClass}.Map{sanitizedBaseType}({sourceVar}.{fieldName})";
            }
            
            // Handle complex types (nur wenn NICHT primitiv/nullable und NICHT enum)
            if (!TypeMappingHelper.IsProtoScalarType(param.FullName) && !param.IsCollection && !param.IsDictionary && !param.IsEnum)
            {
                var typeName = GetSimpleTypeName(param.FullName);
                var sanitizedTypeName = NameSanitizer.SanitizeName(typeName);
                
                // Determine correct helper class based on DomainType
                var domainType = typeLookup != null ? GetDomainTypeForTypeName(typeName, typeLookup) : DomainType.Object;
                var helperClass = GetHelperClassName(domainType);
                
                return $"{helperClass}.Map{sanitizedTypeName}({sourceVar}.{fieldName})";
            }
            
            // Handle collections
            if (param.IsCollection)
            {
                var elementType = param.CollectionElementType;
                
                // NEU: Collection von nullable Enums (z.B. IReadOnlyList<Klassifikation?>)
                // In Proto als repeated string dargestellt
                if (IsNullableEnumType(elementType))
                {
                    var baseEnumType = GetSimpleTypeName(GetNullableBaseType(elementType));
                    var sanitizedEnumType = NameSanitizer.SanitizeName(baseEnumType);
                    // string → Klassifikation?, leerer String = null
                    return $"{sourceVar}.{fieldName}?.Select(x => string.IsNullOrEmpty(x) ? ({sanitizedEnumType}?)null : Enum.Parse<{sanitizedEnumType}>(x)).ToList()";
                }
                
                // Collection von non-nullable Enums (z.B. IReadOnlyList<Klassifikation>)
                // In Proto als repeated int32 dargestellt → Cast
                if (IsKnownEnumType(elementType))
                {
                    var enumTypeName = GetSimpleTypeName(elementType);
                    var sanitizedEnumType = NameSanitizer.SanitizeName(enumTypeName);
                    return $"{sourceVar}.{fieldName}?.Select(x => ({sanitizedEnumType})x).ToList()";
                }
                
                if (TypeMappingHelper.IsProtoScalarType(elementType) || IsPrimitiveOrNullableType(elementType))
                {
                    return $"{sourceVar}.{fieldName}?.ToList()";
                }
                else
                {
                    var elementTypeName = GetSimpleTypeName(elementType);
                    var sanitizedElementType = NameSanitizer.SanitizeName(elementTypeName);
                    
                    // Determine correct helper class based on element's DomainType
                    var elementDomainType = typeLookup != null ? GetDomainTypeForTypeName(elementTypeName, typeLookup) : DomainType.Object;
                    var helperClass = GetHelperClassName(elementDomainType);
                    
                    return $"{sourceVar}.{fieldName}?.Select(x => {helperClass}.Map{sanitizedElementType}(x)).ToList()";
                }
            }
            
            // Scalar types
            return $"{sourceVar}.{fieldName}";
        }

        private string GeneratePropertyMapping(TypeNode param, string sourceVar, string propName, Dictionary<string, DomainType> typeLookup = null)
        {
            // Enum-Handling — unterscheide zwischen nullable und non-nullable
            if (param.IsEnum)
            {
                var typeName = GetSimpleTypeName(param.FullName);
                var sanitizedTypeName = NameSanitizer.SanitizeName(typeName);
                
                // Nullable Enum (z.B. Klassifikation?) - in Proto als string dargestellt
                if (param.FullName.EndsWith("?"))
                {
                    // C# Nullable Enum → Proto string
                    // null = leerer String, sonst Enum.ToString()
                    return $"{sourceVar}.{propName}?.ToString() ?? string.Empty";
                }
                else
                {
                    // Non-nullable Enum - in Proto als int32 dargestellt
                    // C# Enum → Proto int32 via Cast
                    return $"(int){sourceVar}.{propName}";
                }
            }
            
            // Handle Guid specially
            if (param.FullName == "System.Guid")
                return $"{sourceVar}.{propName}.ToString()";
            
            // Handle decimal (von decimal zu string)
            if (param.FullName == "decimal" || param.FullName == "System.Decimal")
                return $"{sourceVar}.{propName}.ToString(CultureInfo.InvariantCulture)";
            
            // Handle DateTime (von DateTimeOffset zu int64) — non-nullable
            if (param.FullName == "System.DateTime" || param.FullName == "System.DateTimeOffset")
                return $"{sourceVar}.{propName}.ToUnixTimeMilliseconds()";
            
            // NEU: Handle nullable DateTime/DateTimeOffset (DateTimeOffset? → int64, null = 0)
            if (IsNullableDateTimeType(param.FullName))
                return $"{sourceVar}.{propName}?.ToUnixTimeMilliseconds() ?? 0";
            
            // WICHTIG: Prüfe zuerst auf primitive/nullable Typen BEVOR complex type check
            if (IsPrimitiveOrNullableType(param.FullName))
            {
                // Nullable string? -> direkt verwenden, null zu leerem String für Proto
                if (param.FullName == "string?" || param.FullName == "System.String?")
                    return $"{sourceVar}.{propName} ?? string.Empty";
                
                // ★ FIX: Nullable bool? → int32 (0=null, 1=true, 2=false)
                // Proto3 hat keinen null-Zustand für bool. Daher kodieren wir
                // bool? als int32: 0 = nicht gesetzt, 1 = true, 2 = false.
                if (param.FullName == "bool?" || param.FullName == "System.Boolean?")
                    return $"{sourceVar}.{propName} switch {{ null => 0, true => 1, false => 2 }}";
                
                // Nullable int? -> Proto int32 hat keinen null-Zustand
                // null wird zu 0 (Proto default)
                if (param.FullName == "int?" || param.FullName == "System.Int32?")
                    return $"{sourceVar}.{propName} ?? 0";
                    
                // Andere Skalartypen direkt verwenden
                return $"{sourceVar}.{propName}";
            }
            
            // NEU: Handle nullable Domain-Typen (z.B. Klassifikation?)
            // Diese nutzen den Mapper des Base-Typs
            if (IsNullableDomainType(param.FullName))
            {
                var baseTypeName = GetNullableBaseType(param.FullName);
                var simpleBaseType = GetSimpleTypeName(baseTypeName);
                
                // Determine correct helper class based on DomainType
                var domainType = typeLookup != null ? GetDomainTypeForTypeName(simpleBaseType, typeLookup) : DomainType.Object;
                var helperClass = GetHelperClassName(domainType);
                
                return $"{helperClass}.MapToDto({sourceVar}.{propName})";
            }
            
            // Handle complex types (nur wenn NICHT primitiv/nullable und NICHT enum)
            if (!TypeMappingHelper.IsProtoScalarType(param.FullName) && !param.IsCollection && !param.IsDictionary && !param.IsEnum)
            {
                var typeName = GetSimpleTypeName(param.FullName);
                
                // Determine correct helper class based on DomainType
                var domainType = typeLookup != null ? GetDomainTypeForTypeName(typeName, typeLookup) : DomainType.Object;
                var helperClass = GetHelperClassName(domainType);
                
                return $"{helperClass}.MapToDto({sourceVar}.{propName})";
            }
            
            // Handle collections
            if (param.IsCollection)
            {
                var elementType = param.CollectionElementType;
                
                // NEU: Collection von nullable Enums (z.B. IReadOnlyList<Klassifikation?>)
                // In Proto als repeated string dargestellt
                if (IsNullableEnumType(elementType))
                {
                    // Klassifikation? → string, null = leerer String
                    return $"{sourceVar}.{propName}?.Select(x => x?.ToString() ?? string.Empty).ToList()";
                }
                
                // Collection von non-nullable Enums (z.B. IReadOnlyList<Klassifikation>)
                // In Proto als repeated int32 → (int)enum
                if (IsKnownEnumType(elementType))
                {
                    return $"{sourceVar}.{propName}?.Select(x => (int)x).ToList()";
                }
                
                if (TypeMappingHelper.IsProtoScalarType(elementType) || IsPrimitiveOrNullableType(elementType))
                {
                    return $"{sourceVar}.{propName}?.ToList()";
                }
                else
                {
                    var elementTypeName = GetSimpleTypeName(elementType);
                    
                    // Determine correct helper class based on element's DomainType
                    var elementDomainType = typeLookup != null ? GetDomainTypeForTypeName(elementTypeName, typeLookup) : DomainType.Object;
                    var helperClass = GetHelperClassName(elementDomainType);
                    
                    return $"{sourceVar}.{propName}?.Select(x => {helperClass}.MapToDto(x)).ToList()";
                }
            }
            
            // Scalar types
            return $"{sourceVar}.{propName}";
        }

        private string GetSimpleTypeName(string fullName)
        {
            if (string.IsNullOrEmpty(fullName)) return fullName;
            
            var withoutGenerics = fullName.Split('<')[0];
            var parts = withoutGenerics.Split('.');
            return parts[parts.Length - 1];
        }

        private string GetNamespace(string fullName)
        {
            if (string.IsNullOrEmpty(fullName)) return "";
            
            var lastDot = fullName.LastIndexOf('.');
            if (lastDot > 0)
                return fullName.Substring(0, lastDot);
            
            return "";
        }

        /// <summary>
        /// Builds a lookup dictionary from type name to DomainType for all known types.
        /// </summary>
        private Dictionary<string, DomainType> BuildTypeLookup(
            List<TypeAggregationResult> objectTypes,
            List<TypeAggregationResult> commandTypes,
            List<TypeAggregationResult> eventTypes,
            List<TypeAggregationResult> queryTypes,
            List<TypeAggregationResult> queryResponseTypes)
        {
            var lookup = new Dictionary<string, DomainType>();
            
            void AddTypes(List<TypeAggregationResult> types, DomainType domainType)
            {
                if (types == null) return;
                foreach (var type in types)
                {
                    var simpleName = GetSimpleTypeName(type.Node.FullName);
                    lookup[simpleName] = domainType;
                    lookup[type.Node.FullName] = domainType;
                }
            }
            
            AddTypes(objectTypes, DomainType.Object);
            AddTypes(commandTypes, DomainType.Command);
            AddTypes(eventTypes, DomainType.Event);
            AddTypes(queryTypes, DomainType.Query);
            AddTypes(queryResponseTypes, DomainType.QueryResponse);
            
            return lookup;
        }

        /// <summary>
        /// Gets the helper class name for a given DomainType.
        /// </summary>
        private string GetHelperClassName(DomainType domainType)
        {
            return domainType switch
            {
                DomainType.Object => "ProtoValueObjectHelpers",
                DomainType.Command => "ProtoCommandMappingHelpers",
                DomainType.Event => "ProtoEventMappingHelpers",
                DomainType.Query => "ProtoQueryMappingHelpers",
                DomainType.QueryResponse => "ProtoQueryResponseMappingHelpers",
                _ => "ProtoValueObjectHelpers"
            };
        }

        /// <summary>
        /// Gets the DomainType for a type name using the lookup, defaulting to Object.
        /// </summary>
        private DomainType GetDomainTypeForTypeName(string typeName, Dictionary<string, DomainType> typeLookup)
        {
            if (string.IsNullOrEmpty(typeName)) return DomainType.Object;
            
            var simpleName = GetSimpleTypeName(typeName);
            
            if (typeLookup.TryGetValue(simpleName, out var domainType))
                return domainType;
            
            if (typeLookup.TryGetValue(typeName, out domainType))
                return domainType;
            
            return DomainType.Object;
        }

        /// <summary>
        /// Prüft ob ein Typ ein nullable DateTime/DateTimeOffset ist.
        /// Diese brauchen spezielle Konvertierung: int64 ↔ DateTimeOffset? mit 0 = null.
        /// </summary>
        private bool IsNullableDateTimeType(string typeName)
        {
            if (string.IsNullOrEmpty(typeName))
                return false;
            
            var nullableDateTimeTypes = new HashSet<string>
            {
                "System.DateTime?",
                "System.DateTimeOffset?",
                "System.Nullable<System.DateTime>",
                "System.Nullable<System.DateTimeOffset>",
            };
            
            return nullableDateTimeTypes.Contains(typeName);
        }

        /// <summary>
        /// Prüft ob ein Typ primitiv oder ein nullable primitiver Typ ist und daher KEINEN Mapper braucht.
        /// Diese Typen sollten nicht als Value Objects behandelt werden!
        /// 
        /// WICHTIG: Diese Methode gibt NUR für primitive Typen true zurück.
        /// Nullable Domain-Typen (z.B. Klassifikation?) brauchen den Mapper des Base-Typs!
        /// </summary>
        private bool IsPrimitiveOrNullableType(string typeName)
        {
            if (string.IsNullOrEmpty(typeName))
                return false;
            
            // Nullable<T> Pattern (System.Nullable<X>)
            if (typeName.StartsWith("System.Nullable<") || typeName.StartsWith("Nullable<"))
            {
                // Extrahiere den inneren Typ und prüfe ob dieser primitiv ist
                var innerType = typeName
                    .Replace("System.Nullable<", "")
                    .Replace("Nullable<", "")
                    .TrimEnd('>');
                return IsPrimitiveOrNullableType(innerType);
            }
            
            // Bekannte primitive/system Typen
            var primitiveTypes = new HashSet<string>
            {
                // Non-nullable
                "string", "System.String",
                "int", "System.Int32",
                "long", "System.Int64",
                "short", "System.Int16",
                "byte", "System.Byte",
                "bool", "System.Boolean",
                "double", "System.Double",
                "float", "System.Single",
                "decimal", "System.Decimal",
                "char", "System.Char",
                "object", "System.Object",
                "System.Guid",
                "System.DateTime",
                "System.DateTimeOffset",
                "System.TimeSpan",
            };
            
            // Direkter Match (non-nullable)
            if (primitiveTypes.Contains(typeName))
                return true;
            
            // Endet mit ? (nullable) - prüfe ob der Base-Typ primitiv ist
            if (typeName.EndsWith("?"))
            {
                var baseType = typeName.TrimEnd('?');
                return primitiveTypes.Contains(baseType);
            }
            
            return false;
        }
        
        /// <summary>
        /// Prüft ob ein Typ ein nullable Domain-Typ ist (z.B. SomeValueObject?).
        /// Diese brauchen den Mapper des Base-Typs, sollen aber nicht als eigenständige
        /// Typen mit eigenem Mapper behandelt werden.
        /// 
        /// WICHTIG: Nullable Enums (z.B. Klassifikation?) sind KEINE nullable Domain-Typen!
        /// Sie haben IsEnum = true und werden via string-Parsing konvertiert.
        /// </summary>
        private bool IsNullableDomainType(string typeName)
        {
            if (string.IsNullOrEmpty(typeName))
                return false;
            
            // Prüfe ob es ein nullable Typ ist (endet auf ? oder ist Nullable<T>)
            bool isNullable = typeName.EndsWith("?") || 
                              typeName.StartsWith("System.Nullable<") || 
                              typeName.StartsWith("Nullable<");
            
            if (!isNullable)
                return false;
            
            // Ist NICHT primitiv und NICHT ein Enum
            if (!IsPrimitiveOrNullableType(typeName) && !IsNullableEnumType(typeName))
                return true;
            
            return false;
        }
        
        /// <summary>
        /// Prüft ob ein Typ ein nullable Enum ist (z.B. Klassifikation? oder Nullable&lt;Klassifikation&gt;).
        /// Diese werden in Proto als string dargestellt und brauchen spezielle Konvertierung.
        /// </summary>
        private bool IsNullableEnumType(string typeName)
        {
            if (string.IsNullOrEmpty(typeName))
                return false;
            
            // Bekannte Enum-Typen aus dem Domain
            // Diese Liste wird erweitert wenn neue Enums hinzukommen
            var knownEnumTypes = new HashSet<string>
            {
                // Domain.ImagePair
                "Klassifikation", "Domain.ImagePair.Klassifikation",
                "BildVersion", "Domain.ImagePair.BildVersion",
                // Domain.Todo  
                "Prioritaet", "Domain.Todo.Prioritaet",
                "TodoStatus", "Domain.Todo.TodoStatus",
            };
            
            string baseType = null;
            
            // Pattern 1: Type? (z.B. "Klassifikation?")
            if (typeName.EndsWith("?"))
            {
                baseType = typeName.TrimEnd('?');
            }
            // Pattern 2: Nullable<Type> oder System.Nullable<Type>
            else if (typeName.StartsWith("System.Nullable<") || typeName.StartsWith("Nullable<"))
            {
                baseType = typeName
                    .Replace("System.Nullable<", "")
                    .Replace("Nullable<", "")
                    .TrimEnd('>');
            }
            
            if (baseType == null)
                return false;
            
            var simpleBaseType = GetSimpleTypeName(baseType);
            
            return knownEnumTypes.Contains(baseType) || knownEnumTypes.Contains(simpleBaseType);
        }
        
        /// <summary>
        /// Prüft ob ein Typname ein bekannter non-nullable Enum-Typ ist.
        /// Nutzt das dynamisch gesammelte _enumTypeNames Set statt einer Hardcoded-Liste.
        /// Wird für Collection-Element-Typen benötigt, wo nur ein String vorliegt
        /// (z.B. "Domain.ImagePair.Klassifikation" als Element von IReadOnlyList&lt;Klassifikation&gt;).
        /// </summary>
        private bool IsKnownEnumType(string typeName)
        {
            if (string.IsNullOrEmpty(typeName)) return false;
            
            // Nullable Typen sind hier NICHT gemeint — dafür gibt es IsNullableEnumType
            if (typeName.EndsWith("?") || typeName.StartsWith("System.Nullable<") || typeName.StartsWith("Nullable<"))
                return false;
            
            var simple = GetSimpleTypeName(typeName);
            return _enumTypeNames.Contains(typeName) || _enumTypeNames.Contains(simple);
        }
        
        /// <summary>
        /// Extrahiert den Base-Typ aus einem nullable Typ.
        /// Beispiel: "Klassifikation?" → "Klassifikation"
        /// </summary>
        private string GetNullableBaseType(string typeName)
        {
            if (string.IsNullOrEmpty(typeName))
                return typeName;
            
            if (typeName.EndsWith("?"))
                return typeName.TrimEnd('?');
            
            // Nullable<T> Pattern
            if (typeName.StartsWith("System.Nullable<") || typeName.StartsWith("Nullable<"))
            {
                return typeName
                    .Replace("System.Nullable<", "")
                    .Replace("Nullable<", "")
                    .TrimEnd('>');
            }
            
            return typeName;
        }

        private string ToPascalCase(string input)
        {
            if (string.IsNullOrEmpty(input)) return input;
            
            var parts = input.Split('_');
            var result = new StringBuilder();
            
            foreach (var part in parts)
            {
                if (part.Length > 0)
                {
                    result.Append(char.ToUpper(part[0]));
                    if (part.Length > 1)
                        result.Append(part.Substring(1));
                }
            }
            
            return result.ToString();
        }

        private void GenerateDebugOutput(
            GeneratorExecutionContext context, 
            List<string> debugInfo,
            List<TypeAggregationResult> objectTypes,
            List<TypeAggregationResult> commandTypes,
            List<TypeAggregationResult> eventTypes,
            List<TypeAggregationResult> queryTypes,
            List<TypeAggregationResult> queryResponseTypes)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// Debug output from DtoMapperSourceGenerator");
            sb.AppendLine();
            sb.AppendLine("/*");
            
            foreach (var line in debugInfo)
            {
                sb.AppendLine($"  {line}");
            }
            
            if (commandTypes != null)
            {
                sb.AppendLine();
                sb.AppendLine("  Commands:");
                foreach (var cmd in commandTypes)
                {
                    sb.AppendLine($"    - {cmd.TypeName}");
                }
            }
            
            if (eventTypes != null)
            {
                sb.AppendLine();
                sb.AppendLine("  Events:");
                foreach (var evt in eventTypes)
                {
                    sb.AppendLine($"    - {evt.TypeName}");
                }
            }
            
            if (queryTypes != null)
            {
                sb.AppendLine();
                sb.AppendLine("  Queries:");
                foreach (var q in queryTypes)
                {
                    sb.AppendLine($"    - {q.TypeName}");
                }
            }
            
            if (queryResponseTypes != null)
            {
                sb.AppendLine();
                sb.AppendLine("  QueryResponses:");
                foreach (var qr in queryResponseTypes)
                {
                    sb.AppendLine($"    - {qr.TypeName}");
                }
            }
            
            if (objectTypes != null)
            {
                sb.AppendLine();
                sb.AppendLine("  Value Objects:");
                foreach (var obj in objectTypes)
                {
                    sb.AppendLine($"    - {obj.TypeName}");
                }
            }
            
            sb.AppendLine("*/");
            
            context.AddSource("DtoMapper.Debug.g.cs", sb.ToString());
        }
    }
}