using Microsoft.CodeAnalysis;
using System.Collections.Generic;
using System.Text;

namespace Infrastructure.SourceGeneration
{
    /// <summary>
    /// Generiert <c>GeneratedEventJson.Serialize/Deserialize</c> — den reflection-freien Dispatch
    /// (Invariante 4) über die persistierbaren Events auf den STJ-Source-Gen-Kontext
    /// <c>Infrastructure.Serialization.EventJsonSerializerContext</c>.
    ///
    /// Zweck:
    /// - Serialize: <c>IEvent → JSON</c> (Schreibpfad; heute Marten-intern, künftig der COPY-Writer).
    /// - Deserialize: <c>(snake_case-Typ, JSON) → IEvent</c> (Lesepfad; der eigene Read der COPY-Tabelle).
    /// - Beide gehen über <c>EventJsonSerializerContext.Default.{Event}</c> → keine Laufzeit-Reflection.
    ///
    /// Drift-Schutz (Compile-Zeit): der Switch referenziert je Event <c>Default.{Event}</c>. Fehlt das
    /// Event im Manifest <c>EventJsonSerializerContext</c>, existiert die Property nicht → Build bricht.
    /// Damit ist die hand-gepflegte <c>[JsonSerializable]</c>-Liste gegen genau diese Event-Menge gekoppelt.
    ///
    /// Der Diskriminator ist der snake_case-Name — IDENTISCH zu <c>MartenEventTypeRegistration</c>
    /// (<c>options.Events.MapEventType(type, snake)</c>) und <c>GeneratedTypeRegistry.PersistableEvents</c>,
    /// damit der künftige COPY-<c>type</c>-Spaltenwert deckungsgleich bleibt.
    /// </summary>
    [Generator]
    public class EventJsonGenerator : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context) { }

        public void Execute(GeneratorExecutionContext context)
        {
            var compilation = context.Compilation;

            var iEvent = compilation.GetTypeByMetadataName("Abstractions.IEvent");
            if (iEvent == null)
                return;
            var iTransient = compilation.GetTypeByMetadataName("Abstractions.ITransientEvent");
            var iSelf = compilation.GetTypeByMetadataName("Abstractions.IPipelineSelfMessage");

            var all = new List<INamedTypeSymbol>();
            Collect(compilation.GlobalNamespace, all);

            // Exakt die Menge aus GeneratedTypeRegistry.PersistableEvents:
            // konkretes IEvent, KEIN ITransientEvent, KEINE Self-Message.
            var events = new List<INamedTypeSymbol>();
            foreach (var t in all)
            {
                var ifaces = t.AllInterfaces;
                if (!ifaces.Contains(iEvent, SymbolEqualityComparer.Default))
                    continue;
                if (iTransient != null && ifaces.Contains(iTransient, SymbolEqualityComparer.Default))
                    continue;
                if (iSelf != null && ifaces.Contains(iSelf, SymbolEqualityComparer.Default))
                    continue;
                events.Add(t);
            }
            events.Sort((a, b) => string.Compare(a.Name, b.Name, System.StringComparison.Ordinal));

            var full = SymbolDisplayFormat.FullyQualifiedFormat;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Text.Json;");
            sb.AppendLine("using Abstractions;");
            sb.AppendLine("using Ctx = global::Infrastructure.Serialization.EventJsonSerializerContext;");
            sb.AppendLine();
            sb.AppendLine("namespace Infrastructure.Serialization;");
            sb.AppendLine();
            sb.AppendLine("/// <summary>");
            sb.AppendLine("/// Reflection-freier Event-JSON-Dispatch (Invariante 4). Generiert vom EventJsonGenerator");
            sb.AppendLine("/// über EventJsonSerializerContext. Diskriminator = snake_case (== Marten-MapEventType).");
            sb.AppendLine("/// </summary>");
            sb.AppendLine("public static class GeneratedEventJson");
            sb.AppendLine("{");

            // ── Serialize: IEvent → JSON ──
            sb.AppendLine("    public static string Serialize(IEvent evt) => evt switch");
            sb.AppendLine("    {");
            foreach (var e in events)
                sb.AppendLine($"        {e.ToDisplayString(full)} x => JsonSerializer.Serialize(x, Ctx.Default.{e.Name}),");
            sb.AppendLine("        _ => throw new NotSupportedException($\"Kein generierter JSON-Serialize-Pfad für {evt.GetType().FullName}\")");
            sb.AppendLine("    };");
            sb.AppendLine();

            // ── Deserialize: (snake_case-Typ, JSON) → IEvent ──
            sb.AppendLine("    public static IEvent Deserialize(string typ, string json) => typ switch");
            sb.AppendLine("    {");
            foreach (var e in events)
                sb.AppendLine($"        \"{Snake(e.Name)}\" => JsonSerializer.Deserialize(json, Ctx.Default.{e.Name})!,");
            sb.AppendLine("        _ => throw new NotSupportedException($\"Unbekannter Event-Typ-Diskriminator: {typ}\")");
            sb.AppendLine("    };");
            sb.AppendLine();

            // ── Diskriminator eines konkreten Events (für den Schreibpfad) ──
            sb.AppendLine("    public static string Diskriminator(IEvent evt) => evt switch");
            sb.AppendLine("    {");
            foreach (var e in events)
                sb.AppendLine($"        {e.ToDisplayString(full)} => \"{Snake(e.Name)}\",");
            sb.AppendLine("        _ => throw new NotSupportedException($\"Kein Diskriminator für {evt.GetType().FullName}\")");
            sb.AppendLine("    };");
            sb.AppendLine();

            // ── Abgedeckte Typen (Test-Orakel gegen GeneratedTypeRegistry.PersistableEventTypes) ──
            sb.AppendLine("    public static readonly IReadOnlyList<Type> AbgedeckteTypen = new Type[]");
            sb.AppendLine("    {");
            foreach (var e in events)
                sb.AppendLine($"        typeof({e.ToDisplayString(full)}),");
            sb.AppendLine("    };");
            sb.AppendLine("}");

            context.AddSource("GeneratedEventJson.g.cs", sb.ToString());
        }

        private static void Collect(INamespaceSymbol ns, List<INamedTypeSymbol> results)
        {
            foreach (var t in ns.GetTypeMembers())
                if (t.TypeKind == TypeKind.Class && !t.IsAbstract && !t.IsStatic)
                    results.Add(t);
            foreach (var sub in ns.GetNamespaceMembers())
                Collect(sub, results);
        }

        // ── snake_case, identisch zu TypeRegistryGenerator (Umlaut-Sanitisierung inklusive) ──
        private static string Snake(string name)
        {
            var s = Sanitize(name);
            if (string.IsNullOrWhiteSpace(s)) return s;
            var sb = new StringBuilder();
            sb.Append(char.ToLowerInvariant(s[0]));
            for (int i = 1; i < s.Length; i++)
            {
                var c = s[i];
                if (char.IsUpper(c)) { sb.Append('_'); sb.Append(char.ToLowerInvariant(c)); }
                else sb.Append(c);
            }
            return sb.ToString();
        }

        private static string Sanitize(string name)
        {
            if (string.IsNullOrEmpty(name)) return name;
            return name
                .Replace("ä", "ae").Replace("ö", "oe").Replace("ü", "ue")
                .Replace("Ä", "Ae").Replace("Ö", "Oe").Replace("Ü", "Ue")
                .Replace("ß", "ss");
        }
    }
}
