using Microsoft.CodeAnalysis;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Infrastructure.SourceGeneration
{
    /// <summary>
    /// Verdrahtungs-Generator für den PULL-Pfad. Findet jede <c>ISubscriber</c>, die zusätzlich
    /// <c>Abstractions.IPullSubscriber</c> implementiert, und emittiert in
    /// <c>Infrastructure</c> (wie GeneratedSubscribers) die komplette, sonst handgeschriebene
    /// Verdrahtung:
    ///   - je Projektion einen per-Stream-Adapter-Kind (<c>IClusterKindContributor</c>),
    ///     der Tracker + Dispatch per DI auflöst (Store-Impl-Typ wird NIE genannt),
    ///   - eine <c>PullPathRegistration</c> (Receiver + Poller, generisch),
    ///   - <c>PushSubscriberExclusions</c> (koppelt den Push-Subscriber ab),
    ///   - <c>AddGeneratedPullPaths()</c>, das der Host als EINZIGEN Aufruf nutzt.
    ///
    /// KEIN handgeschriebener Domänen-Glue im Framework mehr — die Domäne steckt nur noch in
    /// der Projektion (Domain.Projections) und ihrem Store (Domain.Infrastructure).
    /// </summary>
    [Generator]
    public class PullPathGenerator : ISourceGenerator
    {
        private const string ISubscriberFullName = "Abstractions.ISubscriber";
        private const string IExactlyOnceFullName = "Abstractions.IPullSubscriber";

        public void Initialize(GeneratorInitializationContext context) { }

        public void Execute(GeneratorExecutionContext context)
        {
            var iSubscriber = context.Compilation.GetTypeByMetadataName(ISubscriberFullName);
            var iExactlyOnce = context.Compilation.GetTypeByMetadataName(IExactlyOnceFullName);
            if (iSubscriber == null || iExactlyOnce == null)
                return;

            var projections = new List<INamedTypeSymbol>();
            void Walk(INamespaceSymbol ns)
            {
                foreach (var t in ns.GetTypeMembers())
                {
                    if (t.TypeKind == TypeKind.Class && !t.IsAbstract &&
                        t.AllInterfaces.Contains(iExactlyOnce, SymbolEqualityComparer.Default))
                        projections.Add(t);
                }
                foreach (var child in ns.GetNamespaceMembers())
                    Walk(child);
            }
            Walk(context.Compilation.GlobalNamespace);

            context.AddSource("GeneratedPullPaths.g.cs",
                GenerateFile(projections.OrderBy(p => p.Name).ToList()));
        }

        private static string GenerateFile(List<INamedTypeSymbol> projections)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// Verdrahtung des Pull-Pfads pro IPullSubscriber (PullPathGenerator).");
            sb.AppendLine("using Abstractions;");
            sb.AppendLine("using Core;");
            sb.AppendLine("using Infrastructure.Projections;");
            sb.AppendLine("using Infrastructure.PubSub;");
            sb.AppendLine("using Infrastructure.PubSub.Startup;");
            sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
            sb.AppendLine("using Proto;");
            sb.AppendLine("using Proto.Cluster;");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Linq;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine();
            sb.AppendLine("namespace Infrastructure.Projections.Generated;");
            sb.AppendLine();

            foreach (var p in projections)
                EmitKind(sb, p);

            sb.AppendLine("public static class GeneratedPullPaths");
            sb.AppendLine("{");
            sb.AppendLine("    public static IServiceCollection AddGeneratedPullPaths(this IServiceCollection services)");
            sb.AppendLine("    {");
            if (projections.Count == 0)
            {
                sb.AppendLine("        // Keine IPullSubscriber gefunden.");
            }
            else
            {
                var names = string.Join(", ", projections.Select(p => "\"" + p.Name + "\""));
                sb.AppendLine($"        services.AddSingleton(new PushSubscriberExclusions(new[] {{ {names} }}));");
                sb.AppendLine();
                foreach (var p in projections)
                {
                    sb.AppendLine($"        services.AddSingleton<IClusterKindContributor, {p.Name}PullAdapterKind>();");
                    sb.AppendLine($"        services.AddSingleton(new PullPathRegistration(");
                    sb.AppendLine($"            {p.Name}PullAdapterKind.KindName, {p.Name}PullAdapterKind.KindName, {p.ToDisplayString()}.SubscribedTypes));");
                }
                sb.AppendLine();
                sb.AppendLine("        services.AddHostedService<GenericPullStartupService>();");
            }
            sb.AppendLine("        return services;");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static void EmitKind(StringBuilder sb, INamedTypeSymbol p)
        {
            var fqProjection = p.ToDisplayString();
            var ctor = p.InstanceConstructors
                .Where(c => c.DeclaredAccessibility == Accessibility.Public && !c.IsStatic)
                .OrderByDescending(c => c.Parameters.Length)
                .FirstOrDefault();
            var storeParams = ctor?.Parameters ?? default;

            sb.AppendLine($"internal sealed class {p.Name}PullAdapterKind : IClusterKindContributor");
            sb.AppendLine("{");
            sb.AppendLine($"    public const string KindName = \"pull-{p.Name}\";");
            sb.AppendLine();
            sb.AppendLine("    public ClusterKind CreateKind(ActorSystem system, IServiceProvider provider)");
            sb.AppendLine("    {");
            sb.AppendLine("        var eventStore = provider.GetRequiredService<IEventStoreRepository>();");
            sb.AppendLine("        var depsSink = provider.GetService<IReadModelDepsSink>();");
            sb.AppendLine("        return new ClusterKind(KindName, Props.FromProducer(() =>");
            sb.AppendLine("            new SignalAdapterActor(eventStore, () =>");
            sb.AppendLine("            {");

            var argNames = new List<string>();
            if (!storeParams.IsDefault)
            {
                for (int i = 0; i < storeParams.Length; i++)
                {
                    var t = storeParams[i].Type.ToDisplayString();
                    sb.AppendLine($"                var s{i} = provider.GetRequiredService<{t}>();");
                    argNames.Add("s" + i);
                }
            }
            sb.AppendLine($"                var projection = new {fqProjection}({string.Join(", ", argNames)});");
            sb.AppendLine($"                var candidates = new object[] {{ {string.Join(", ", argNames)} }};");
            sb.AppendLine("                var trackers = candidates.OfType<IProjectionTracker>().ToList();");
            sb.AppendLine("                if (trackers.Count > 1)");
            sb.AppendLine($"                    throw new InvalidOperationException(\"{p.Name}: mehrere IProjectionTracker-Stores — höchstens einer erlaubt (Spec 7.6).\");");
            sb.AppendLine();
            sb.AppendLine("                // Schritt A / Spec 8: DIESELBE Ausgabe-Route wie der Push-Actor (HandlerOutputRouter):");
            sb.AppendLine("                //   IEvent → re-publish, ICommand → Reaktion. system.Cluster() hier zur SPAWN-Zeit");
            sb.AppendLine("                //   (die Factory läuft im Actor-Started, Cluster ist fertig — NICHT bei Kind-Registrierung).");
            sb.AppendLine("                //   DetachedEmit hält den virtuellen Adapter-Turn frei (at-least-once, Empfänger dedupliziert).");
            sb.AppendLine("                var router = new HandlerOutputRouter(");
            sb.AppendLine("                    system.Cluster(), provider.GetService<BrokerPublisher>(), projection.SubscriberId);");
            sb.AppendLine("                Func<EventEnvelope, ProjectionWriter, Task> dispatch =");
            sb.AppendLine("                    (e, writer) => projection.DispatchAsync(e, writer,");
            sb.AppendLine("                        DetachedEmit.Wrap(router.EmitFor(e, System.Threading.CancellationToken.None)));");
            sb.AppendLine("                return (projection.SubscriberId, trackers.FirstOrDefault(), dispatch);");
            sb.AppendLine("            }, depsSink)));");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();
        }
    }
}
