using Microsoft.CodeAnalysis;
using System;
using System.Collections.Generic;
using System.Text;

namespace Infrastructure.SourceGeneration
{
    /// <summary>
    /// Generiert <c>GeneratedSignalFactory.Create(IEvent, streamId, version)</c> — die
    /// reflection-freie Zuordnung Event → Signal (Invariante 4). Der Aggregat-Actor ruft
    /// sie nach dem Commit auf, um zusätzlich zum rohen Event das passende
    /// `StateChangeVia{Event}`-Signal zu veröffentlichen (Spec 4.3, Emit-Wiring).
    ///
    /// Zuordnung per Konvention: zu einem Signal `{ns}.StateChangeVia{X}` gehört das
    /// Event `{ns}.{X}`. Läuft auf Infrastructure und sieht Domain.dll über die
    /// Compilation (GlobalNamespace) — Events UND Signale sind dort bereits kompiliert.
    ///
    /// Transiente Events haben kein Signal → für sie liefert die Factory <c>null</c>
    /// (der `_ => null`-Arm), und der Actor publiziert dann nur das Event.
    /// </summary>
    [Generator]
    public class SignalFactoryGenerator : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context) { }

        public void Execute(GeneratorExecutionContext context)
        {
            var compilation = context.Compilation;

            // ★ P1b (TG-1): die Event→Signal-Kante wird TYP-getrieben aus dem generischen Marker
            //   IStateChangeSignal<TEvent> gelesen — NICHT mehr per Namens-Präfix „StateChangeVia" +
            //   Namespace-Namenslookup. Ein Signal deklariert sein Event im Typ-Argument.
            var signalOpenGeneric = compilation.GetTypeByMetadataName("Abstractions.IStateChangeSignal`1");
            if (signalOpenGeneric == null)
                return;

            var allTypes = new List<INamedTypeSymbol>();
            Collect(compilation.GlobalNamespace, allTypes);

            var pairs = new List<(string EventType, string SignalType)>();

            foreach (var type in allTypes)
            {
                INamedTypeSymbol? marker = null;
                foreach (var i in type.AllInterfaces)
                {
                    if (i.IsGenericType &&
                        SymbolEqualityComparer.Default.Equals(i.OriginalDefinition, signalOpenGeneric))
                    {
                        marker = i;
                        break;
                    }
                }
                if (marker == null)
                    continue;

                var eventType = marker.TypeArguments[0];
                pairs.Add((eventType.ToDisplayString(), type.ToDisplayString()));
            }

            pairs.Sort((a, b) => string.Compare(a.EventType, b.EventType, StringComparison.Ordinal));

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using Abstractions;");
            sb.AppendLine();
            sb.AppendLine("namespace Infrastructure.Mapping;");
            sb.AppendLine();
            sb.AppendLine("/// <summary>");
            sb.AppendLine("/// Reflection-freie Event→Signal-Zuordnung (Invariante 4). Generiert vom");
            sb.AppendLine("/// SignalFactoryGenerator. null = das Event hat kein Signal (transiente Events).");
            sb.AppendLine("/// </summary>");
            sb.AppendLine("public static class GeneratedSignalFactory");
            sb.AppendLine("{");
            sb.AppendLine("    public static IStateChangeSignal? Create(IEvent evt, System.Guid streamId, int version)");
            sb.AppendLine("        => evt switch");
            sb.AppendLine("        {");
            foreach (var (evtType, sigType) in pairs)
                sb.AppendLine($"            {evtType} => new {sigType}(streamId, version),");
            sb.AppendLine("            _ => null");
            sb.AppendLine("        };");
            sb.AppendLine("}");

            context.AddSource("GeneratedSignalFactory.g.cs", sb.ToString());

            // ── Zusätzlich: Event-Typ → Signal-Typ (für die Signal-Subscription der Receiver) ──
            var routes = new StringBuilder();
            routes.AppendLine("// <auto-generated/>");
            routes.AppendLine("#nullable enable");
            routes.AppendLine("using System;");
            routes.AppendLine("using System.Collections.Generic;");
            routes.AppendLine();
            routes.AppendLine("namespace Infrastructure.Mapping;");
            routes.AppendLine();
            routes.AppendLine("/// <summary>");
            routes.AppendLine("/// Event-Typ → Signal-Typ. Ein Receiver leitet daraus ab, welche");
            routes.AppendLine("/// StateChangeVia{Event}-Signale er für die Events seiner Projektion");
            routes.AppendLine("/// abonnieren muss. Generiert vom SignalFactoryGenerator.");
            routes.AppendLine("/// </summary>");
            routes.AppendLine("public static class GeneratedSignalRoutes");
            routes.AppendLine("{");
            routes.AppendLine("    public static readonly IReadOnlyDictionary<Type, Type> EventToSignal = new Dictionary<Type, Type>");
            routes.AppendLine("    {");
            foreach (var (evtType, sigType) in pairs)
                routes.AppendLine($"        [typeof({evtType})] = typeof({sigType}),");
            routes.AppendLine("    };");
            routes.AppendLine("}");

            context.AddSource("GeneratedSignalRoutes.g.cs", routes.ToString());
        }

        private void Collect(INamespaceSymbol ns, List<INamedTypeSymbol> results)
        {
            foreach (var type in ns.GetTypeMembers())
            {
                if (type.TypeKind == TypeKind.Class && !type.IsAbstract && !type.IsStatic)
                    results.Add(type);
            }

            foreach (var subNs in ns.GetNamespaceMembers())
                Collect(subNs, results);
        }
    }
}
