using Microsoft.CodeAnalysis;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Infrastructure.SourceGeneration
{
    /// <summary>
    /// Generiert die Snapshot-Ablage-Naht (docs/snapshot-konzept.md §8) reflection-frei:
    ///
    /// 1. <c>Infrastructure.Persistence.RegisteredSnapshotTypes.Register(StoreOptions)</c> — registriert je
    ///    IState-Aggregat den Marten-Dokumenttyp <c>Snapshot&lt;TState&gt;</c> mit sauberem Tabellen-Alias
    ///    (<c>snapshot_konto</c> → <c>es.mt_doc_snapshot_konto</c>) und Identität = <c>Id</c> (die Aggregat-GUID).
    ///
    /// 2. <c>Infrastructure.Persistence.GeneratedSnapshotSchema.VersionOf&lt;TState&gt;()</c> — der zur
    ///    Compile-Zeit berechnete Struktur-Hash des State-Typs. Ändert sich die State-Form (Property-Namen/
    ///    Typen), ändert sich der Hash → alte Snapshots invalidieren automatisch (zero-touch, Invariante 5).
    ///
    /// Symbol-Enumeration wie im <see cref="AggregateActorGenerator"/> (Infrastructure sieht die Domain-Symbole).
    /// </summary>
    [Generator]
    public class SnapshotRegistrationGenerator : ISourceGenerator
    {
        private const string IStateInterfaceFullName = "Abstractions.IState";

        public void Initialize(GeneratorInitializationContext context) { }

        public void Execute(GeneratorExecutionContext context)
        {
            var states = FindIStateImplementations(context.Compilation)
                .OrderBy(s => s.Name)
                .ToList();
            if (states.Count == 0) return;

            context.AddSource("GeneratedSnapshotRegistration.g.cs", Build(states));
        }

        private static string Build(List<INamedTypeSymbol> states)
        {
            var namespaces = new HashSet<string>();
            foreach (var s in states) namespaces.Add(s.ContainingNamespace.ToDisplayString());

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using Abstractions;");
            sb.AppendLine("using Marten;");
            foreach (var ns in namespaces.OrderBy(n => n))
                sb.AppendLine($"using {ns};");
            sb.AppendLine();
            sb.AppendLine("namespace Infrastructure.Persistence;");
            sb.AppendLine();

            // ── Struktur-Hash je State-Typ ──
            sb.AppendLine("/// <summary>Compile-zeitige Struktur-Hashes der State-Typen (Snapshot-Schema-Version).</summary>");
            sb.AppendLine("public static class GeneratedSnapshotSchema");
            sb.AppendLine("{");
            sb.AppendLine("    private static readonly IReadOnlyDictionary<Type, string> _byType = new Dictionary<Type, string>");
            sb.AppendLine("    {");
            foreach (var s in states)
                sb.AppendLine($"        [typeof({s.Name})] = \"{StructuralHash(s)}\",");
            sb.AppendLine("    };");
            sb.AppendLine();
            sb.AppendLine("    /// <summary>Struktur-Version des State-Typs; leer, wenn unbekannt.</summary>");
            sb.AppendLine("    public static string VersionOf<TState>() where TState : class, IState");
            sb.AppendLine("        => _byType.TryGetValue(typeof(TState), out var v) ? v : \"\";");
            sb.AppendLine("}");
            sb.AppendLine();

            // ── Marten-Dokumenttyp-Registrierung ──
            sb.AppendLine("/// <summary>Registriert die Snapshot-Dokumenttypen bei Marten (ein jsonb-Dokument je Aggregat-Typ).</summary>");
            sb.AppendLine("public static class RegisteredSnapshotTypes");
            sb.AppendLine("{");
            sb.AppendLine("    public static void Register(StoreOptions options)");
            sb.AppendLine("    {");
            foreach (var s in states)
            {
                var alias = "snapshot_" + s.Name.ToLowerInvariant();
                sb.AppendLine($"        options.Schema.For<Snapshot<{s.Name}>>().Identity(x => x.Id).DocumentAlias(\"{alias}\");");
            }
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        /// <summary>
        /// Deterministischer FNV-1a-Hash über die sortierte Property-Signatur (Name:Typ) des States.
        /// Stabil über Builds, ändert sich bei jeder Formänderung.
        /// </summary>
        private static string StructuralHash(INamedTypeSymbol state)
        {
            var props = state.GetMembers()
                .OfType<IPropertySymbol>()
                .Where(p => p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic)
                .Select(p => $"{p.Name}:{p.Type.ToDisplayString()}")
                .OrderBy(x => x, System.StringComparer.Ordinal);

            var signature = string.Join(";", props);

            unchecked
            {
                const uint offset = 2166136261;
                const uint prime = 16777619;
                uint hash = offset;
                foreach (var b in Encoding.UTF8.GetBytes(signature))
                {
                    hash ^= b;
                    hash *= prime;
                }
                return hash.ToString("x8");
            }
        }

        private static List<INamedTypeSymbol> FindIStateImplementations(Compilation compilation)
        {
            var results = new List<INamedTypeSymbol>();
            var iState = compilation.GetTypeByMetadataName(IStateInterfaceFullName);
            if (iState == null) return results;

            void Walk(INamespaceSymbol ns)
            {
                foreach (var type in ns.GetTypeMembers())
                    if (type.TypeKind == TypeKind.Class && !type.IsAbstract &&
                        type.AllInterfaces.Contains(iState, SymbolEqualityComparer.Default))
                        results.Add(type);

                foreach (var sub in ns.GetNamespaceMembers()) Walk(sub);
            }

            Walk(compilation.GlobalNamespace);
            return results;
        }
    }
}
