// In Projekt: Infrastructure.SourceGeneration
// Dateiname: SubscriberActorGenerator.cs

using Microsoft.CodeAnalysis;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Infrastructure.SourceGeneration
{
    /// <summary>
    /// Generiert für jede ISubscriber-Implementierung:
    /// 
    /// 1. SubscriberActors.g.cs — Actor-Klassen (XyzActor : SubscriberActorBase&lt;Xyz&gt;)
    /// 2. GeneratedSubscribers.g.cs — DI-Registrierung + Spawn-Infos
    /// 
    /// ★ Phase 3: DispatchAsync nutzt IAggregateEnvelope statt IMessageEnvelope.
    ///   Events haben immer Aggregate-Kontext.
    ///
    /// Gegenstück zu AggregateActorGenerator (Aggregate-Seite).
    /// Ersetzt: SubscriberActors.cs, GeneratedSubscribers.cs (händisch)
    /// </summary>
    [Generator]
    public class SubscriberActorGenerator : ISourceGenerator
    {
        private const string ISubscriberInterfaceFullName = "Abstractions.ISubscriber";

        public void Initialize(GeneratorInitializationContext context)
        {
        }

        public void Execute(GeneratorExecutionContext context)
        {
            List<INamedTypeSymbol> subscriberSymbols = FindISubscriberImplementations(context.Compilation);

            if (subscriberSymbols.Count == 0)
            {
                return;
            }

            var sorted = subscriberSymbols.OrderBy(s => s.Name).ToList();

            string actorsSource = GenerateSubscriberActorsFile(sorted);
            string registrationSource = GenerateSubscribersRegistrationFile(sorted);

            context.AddSource("SubscriberActors.g.cs", actorsSource);
            context.AddSource("GeneratedSubscribers.g.cs", registrationSource);
        }

        private List<INamedTypeSymbol> FindISubscriberImplementations(Compilation compilation)
        {
            var results = new List<INamedTypeSymbol>();
            INamedTypeSymbol? iSubscriberInterface = compilation.GetTypeByMetadataName(ISubscriberInterfaceFullName);

            if (iSubscriberInterface == null)
            {
                return results;
            }

            void FindTypes(INamespaceSymbol namespaceSymbol)
            {
                foreach (var type in namespaceSymbol.GetTypeMembers())
                {
                    if (type.TypeKind == TypeKind.Class &&
                        !type.IsAbstract &&
                        type.AllInterfaces.Contains(iSubscriberInterface, SymbolEqualityComparer.Default))
                    {
                        results.Add(type);
                    }
                }

                foreach (var subNamespace in namespaceSymbol.GetNamespaceMembers())
                {
                    FindTypes(subNamespace);
                }
            }

            FindTypes(compilation.GlobalNamespace);
            return results;
        }

        /// <summary>
        /// Generiert Actor-Klassen für alle Subscriber.
        /// 
        /// ★ Phase 3: DispatchAsync mit IAggregateEnvelope
        /// </summary>
        private string GenerateSubscriberActorsFile(List<INamedTypeSymbol> subscriberSymbols)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// Subscriber-Actors delegieren an ISubscriber-Logik-Klassen");
            sb.AppendLine("// ★ Phase 3: DispatchAsync mit IAggregateEnvelope");
            sb.AppendLine();

            var namespaces = new HashSet<string>();
            foreach (var symbol in subscriberSymbols)
            {
                namespaces.Add(symbol.ContainingNamespace.ToDisplayString());
            }

            sb.AppendLine("using Abstractions;");
            sb.AppendLine("using Core;");
            sb.AppendLine("using Infrastructure.Projections;");
            foreach (var ns in namespaces.OrderBy(n => n))
            {
                sb.AppendLine($"using {ns};");
            }
            sb.AppendLine();

            sb.AppendLine("namespace Infrastructure.PubSub.Actors;");
            sb.AppendLine();

            foreach (var symbol in subscriberSymbols)
            {
                string name = symbol.Name;
                string actorName = $"{name}Actor";

                sb.AppendLine($"public class {actorName} : SubscriberActorBase<{name}>");
                sb.AppendLine("{");

                sb.AppendLine($"    public {actorName}(");
                sb.AppendLine($"        {name} logic,");
                sb.AppendLine($"        BrokerPublisher? publisher = null,");
                sb.AppendLine($"        ReadModelDepsWriter? depsWriter = null)");
                sb.AppendLine($"        : base(logic, publisher, depsWriter) {{ }}");
                sb.AppendLine();

                sb.AppendLine($"    protected override IReadOnlyList<Type> GetSubscribedMessageTypes()");
                sb.AppendLine($"        => {name}.SubscribedTypes;");
                sb.AppendLine();

                // ★ Phase 3: IAggregateEnvelope statt IMessageEnvelope
                sb.AppendLine($"    protected override Task DispatchAsync(");
                sb.AppendLine($"        IAggregateEnvelope envelope, ProjectionWriter writer, Func<IEvent, Task> emit)");
                sb.AppendLine($"        => _logic.DispatchAsync(envelope, writer, emit);");

                sb.AppendLine("}");
                sb.AppendLine();
            }

            return sb.ToString();
        }

        /// <summary>
        /// Generiert DI-Registrierung und Spawn-Infos.
        /// Unverändert (DI ist signaturunabhängig).
        /// </summary>
        private string GenerateSubscribersRegistrationFile(List<INamedTypeSymbol> subscriberSymbols)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// DI-Registrierung für Subscriber-Actors");
            sb.AppendLine();

            var namespaces = new HashSet<string>();
            foreach (var symbol in subscriberSymbols)
            {
                namespaces.Add(symbol.ContainingNamespace.ToDisplayString());
            }

            foreach (var ns in namespaces.OrderBy(n => n))
            {
                sb.AppendLine($"using {ns};");
            }
            sb.AppendLine("using Abstractions;");
            sb.AppendLine("using Infrastructure.Projections;");
            sb.AppendLine("using Infrastructure.PubSub.Actors;");
            sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
            sb.AppendLine("using Proto;");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine();

            sb.AppendLine("namespace Infrastructure.PubSub.Startup;");
            sb.AppendLine();

            sb.AppendLine("public static class GeneratedSubscribers");
            sb.AppendLine("{");

            sb.AppendLine("    public static IServiceCollection RegisterAllSubscribers(IServiceCollection services)");
            sb.AppendLine("    {");

            foreach (var symbol in subscriberSymbols)
            {
                sb.AppendLine($"        services.AddSingleton<{symbol.Name}>();");
            }

            sb.AppendLine();
            sb.AppendLine("        services.AddSingleton<ReadModelDepsWriter>();");
            sb.AppendLine();
            sb.AppendLine("        return services;");
            sb.AppendLine("    }");
            sb.AppendLine();

            sb.AppendLine("    public static IEnumerable<(string Name, Props Props)> GetSubscriberSpawnInfos(");
            sb.AppendLine("        IServiceProvider provider,");
            sb.AppendLine("        BrokerPublisher publisher)");
            sb.AppendLine("    {");
            sb.AppendLine("        var depsWriter = provider.GetRequiredService<ReadModelDepsWriter>();");
            sb.AppendLine();

            foreach (var symbol in subscriberSymbols)
            {
                string name = symbol.Name;
                string actorName = $"{name}Actor";

                sb.AppendLine($"        yield return (");
                sb.AppendLine($"            \"{name}\",");
                sb.AppendLine($"            Props.FromProducer(() =>");
                sb.AppendLine($"            {{");
                sb.AppendLine($"                var logic = provider.GetRequiredService<{name}>();");
                sb.AppendLine($"                return new {actorName}(logic, publisher, depsWriter);");
                sb.AppendLine($"            }})");
                sb.AppendLine($"        );");
                sb.AppendLine();
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }
    }
}