using Microsoft.CodeAnalysis;
using System.Collections.Generic;
using System.Text;

namespace Infrastructure.SourceGeneration
{
    /// <summary>
    /// Generiert den reflexionsfreien (Invariante 4) Wire-Dispatch für den internen Actor-Plane:
    ///
    /// - <c>GeneratedWire</c> — Top-Level-Hüllen (alle <c>IWireMessage</c>): <c>Serialize(object)→byte[]</c>,
    ///   <c>Deserialize(byte[], typeName)→object</c>, <c>TypeName(object)</c>, <c>CanSerialize(Type)</c>
    ///   (Whitelist) und <c>WireMessageTypes</c>. Verwendet vom <c>CqrsWireSerializer</c> (Proto.Remote-ISerializer)
    ///   und vom <c>WireSerializerBootCheck</c>.
    /// - <c>GeneratedWirePoly</c> — die polymorphen Payloads (alle <c>ICommand</c>/<c>IEvent</c>):
    ///   <c>Write/Read/Diskriminator</c> je Wurzel. Verwendet von den <c>WirePolyConverters</c>.
    ///
    /// Alles geht über <c>CqrsWireJsonContext.Default.{Typ}</c> → keine Laufzeit-Reflection. Der Switch
    /// referenziert je Typ <c>Default.{Typ}</c>: fehlt der Typ im hand-gepflegten <c>CqrsWireJsonContext</c>,
    /// existiert die Property nicht → Build bricht (Compile-Zeit-Drift-Guard, exakt EventJsonGenerator-Muster).
    ///
    /// Diskriminator = Typ-Name (PascalCase), identisch zu den <c>GeneratedTypeRegistry</c>-Schlüsseln.
    /// Beide Nodes laufen identischen Generat-Code → Diskriminator- und SerializerId-Konsistenz ist garantiert.
    ///
    /// Discovery deckungsgleich mit <c>TypeRegistryGenerator</c>: konkrete Klassen (nicht abstract/static),
    /// <c>IPipelineSelfMessage</c> ausgeschlossen, Kategorie per <c>AllInterfaces</c>-Enthaltung.
    /// </summary>
    [Generator]
    public class WireSerializerGenerator : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context) { }

        public void Execute(GeneratorExecutionContext context)
        {
            var compilation = context.Compilation;

            var iWire = compilation.GetTypeByMetadataName("Abstractions.IWireMessage");
            var iCommand = compilation.GetTypeByMetadataName("Abstractions.ICommand");
            var iEvent = compilation.GetTypeByMetadataName("Abstractions.IEvent");
            if (iWire == null || iCommand == null || iEvent == null)
                return;
            var iSelf = compilation.GetTypeByMetadataName("Abstractions.IPipelineSelfMessage");
            var iSignal = compilation.GetTypeByMetadataName("Abstractions.IStateChangeSignal");

            var all = new List<INamedTypeSymbol>();
            Collect(compilation.GlobalNamespace, all);

            // Top-Level (wire): alle IWireMessage. Konkrete IPipelineTrigger sind über
            // IPipelineTrigger : IWireMessage automatisch dabei (werden direkt als Cluster-Nachricht gesendet).
            var wire = new List<INamedTypeSymbol>();
            var commands = new List<INamedTypeSymbol>();
            var events = new List<INamedTypeSymbol>();
            var signals = new List<INamedTypeSymbol>();

            foreach (var t in all)
            {
                var ifaces = t.AllInterfaces;
                if (iSelf != null && ifaces.Contains(iSelf, SymbolEqualityComparer.Default))
                    continue;
                if (ifaces.Contains(iWire, SymbolEqualityComparer.Default))
                    wire.Add(t);
                if (ifaces.Contains(iCommand, SymbolEqualityComparer.Default))
                    commands.Add(t);
                if (ifaces.Contains(iEvent, SymbolEqualityComparer.Default))
                    events.Add(t);
                if (iSignal != null && ifaces.Contains(iSignal, SymbolEqualityComparer.Default))
                    signals.Add(t);
            }

            wire.Sort(ByName);
            commands.Sort(ByName);
            events.Sort(ByName);
            signals.Sort(ByName);

            var full = SymbolDisplayFormat.FullyQualifiedFormat;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Text.Json;");
            sb.AppendLine("using Abstractions;");
            sb.AppendLine("using Ctx = global::Infrastructure.Serialization.CqrsWireJsonContext;");
            sb.AppendLine();
            sb.AppendLine("namespace Infrastructure.Serialization;");
            sb.AppendLine();

            // ══════════════════ GeneratedWire (Top-Level) ══════════════════
            sb.AppendLine("/// <summary>Reflexionsfreier Top-Level-Wire-Dispatch (IWireMessage). Generiert.</summary>");
            sb.AppendLine("public static class GeneratedWire");
            sb.AppendLine("{");

            sb.AppendLine("    public static byte[] Serialize(object message) => message switch");
            sb.AppendLine("    {");
            foreach (var w in wire)
                sb.AppendLine($"        {w.ToDisplayString(full)} x => JsonSerializer.SerializeToUtf8Bytes(x, Ctx.Default.{w.Name}),");
            sb.AppendLine("        _ => throw new NotSupportedException($\"Kein Wire-Serialize-Pfad für {message.GetType().FullName}\")");
            sb.AppendLine("    };");
            sb.AppendLine();

            sb.AppendLine("    public static object Deserialize(byte[] bytes, string typeName) => typeName switch");
            sb.AppendLine("    {");
            foreach (var w in wire)
                sb.AppendLine($"        \"{w.Name}\" => JsonSerializer.Deserialize(bytes, Ctx.Default.{w.Name})!,");
            sb.AppendLine("        _ => throw new NotSupportedException($\"Unbekannter Wire-Typ-Diskriminator: {typeName}\")");
            sb.AppendLine("    };");
            sb.AppendLine();

            sb.AppendLine("    public static string TypeName(object message) => message switch");
            sb.AppendLine("    {");
            foreach (var w in wire)
                sb.AppendLine($"        {w.ToDisplayString(full)} => \"{w.Name}\",");
            sb.AppendLine("        _ => throw new NotSupportedException($\"Kein Wire-TypeName für {message.GetType().FullName}\")");
            sb.AppendLine("    };");
            sb.AppendLine();

            sb.AppendLine("    public static bool CanSerialize(Type type) =>");
            if (wire.Count == 0)
            {
                sb.AppendLine("        false;");
            }
            else
            {
                for (int i = 0; i < wire.Count; i++)
                {
                    var sep = i == wire.Count - 1 ? ";" : " ||";
                    sb.AppendLine($"        type == typeof({wire[i].ToDisplayString(full)}){sep}");
                }
            }
            sb.AppendLine();

            sb.AppendLine("    public static readonly IReadOnlyList<Type> WireMessageTypes = new Type[]");
            sb.AppendLine("    {");
            foreach (var w in wire)
                sb.AppendLine($"        typeof({w.ToDisplayString(full)}),");
            sb.AppendLine("    };");
            sb.AppendLine("}");
            sb.AppendLine();

            // ══════════════════ GeneratedWirePoly (geschachtelte Payloads) ══════════════════
            sb.AppendLine("/// <summary>Reflexionsfreier Dispatch für die polymorphen Wire-Payloads. Generiert.</summary>");
            sb.AppendLine("public static class GeneratedWirePoly");
            sb.AppendLine("{");
            EmitPoly(sb, "Event", "IEvent", events, full);
            sb.AppendLine();
            EmitPoly(sb, "Command", "ICommand", commands, full);
            sb.AppendLine();
            EmitPoly(sb, "Signal", "IStateChangeSignal", signals, full);
            sb.AppendLine("}");

            context.AddSource("GeneratedWire.g.cs", sb.ToString());
        }

        private static void EmitPoly(StringBuilder sb, string kind, string iface, List<INamedTypeSymbol> types, SymbolDisplayFormat full)
        {
            // Diskriminator
            sb.AppendLine($"    public static string {kind}Diskriminator({iface} value) => value switch");
            sb.AppendLine("    {");
            foreach (var t in types)
                sb.AppendLine($"        {t.ToDisplayString(full)} => \"{t.Name}\",");
            sb.AppendLine($"        _ => throw new NotSupportedException($\"Kein Wire-Diskriminator für {{value.GetType().FullName}}\")");
            sb.AppendLine("    };");
            sb.AppendLine();

            // Write (nur das Objekt; die Array-Hülle + Diskriminator schreibt der Converter)
            sb.AppendLine($"    public static void Write{kind}(Utf8JsonWriter writer, {iface} value)");
            sb.AppendLine("    {");
            sb.AppendLine("        switch (value)");
            sb.AppendLine("        {");
            foreach (var t in types)
                sb.AppendLine($"            case {t.ToDisplayString(full)} x: JsonSerializer.Serialize(writer, x, Ctx.Default.{t.Name}); break;");
            sb.AppendLine($"            default: throw new NotSupportedException($\"Kein Wire-Write-Pfad für {{value.GetType().FullName}}\");");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();

            // Read
            sb.AppendLine($"    public static {iface} Read{kind}(string diskriminator, ref Utf8JsonReader reader) => diskriminator switch");
            sb.AppendLine("    {");
            foreach (var t in types)
                sb.AppendLine($"        \"{t.Name}\" => JsonSerializer.Deserialize(ref reader, Ctx.Default.{t.Name})!,");
            sb.AppendLine($"        _ => throw new NotSupportedException($\"Unbekannter Wire-{kind}-Diskriminator: {{diskriminator}}\")");
            sb.AppendLine("    };");
        }

        private static int ByName(INamedTypeSymbol a, INamedTypeSymbol b)
            => string.Compare(a.Name, b.Name, System.StringComparison.Ordinal);

        private static void Collect(INamespaceSymbol ns, List<INamedTypeSymbol> results)
        {
            foreach (var t in ns.GetTypeMembers())
                if (t.TypeKind == TypeKind.Class && !t.IsAbstract && !t.IsStatic)
                    results.Add(t);
            foreach (var sub in ns.GetNamespaceMembers())
                Collect(sub, results);
        }
    }
}
