using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;

namespace Cqrs.Codegen;

/// <summary>
/// Erzeugt die beiden STJ-<c>[JsonSerializable]</c>-Manifeste KOMPLETT als echte Quelle, damit der
/// eingebaute STJ-Source-Generator sie beim Hauptbuild als Hand-Quelle sieht und <c>JsonTypeInfo</c> baut.
///
/// ── Warum die GANZE Datei (kein Partial-Split) ──
/// Der STJ-Generator kombiniert <c>[JsonSerializable]</c> NICHT zuverlässig über mehrere partielle
/// Deklarationen (er erzeugt dann die abstrakten Member gar nicht → CS0534). Deshalb emittiert der Prepass
/// je Kontext EINE einzige Deklaration — exakt die Form, die vorher hand-geschrieben funktioniert hat.
///
/// ── Zwei Anteile ──
/// 1. FRAMEWORK-Kopf (Konstante hier): Optionen + Converter + die stabilen, NICHT mit der Domäne wachsenden
///    Typen (Wire-Hüllen, Prozess-/Inbox-Events, <c>CommandFailed</c>). Wächst ein neuer Framework-Hüllentyp
///    hinzu (selten), wird er HIER ergänzt.
/// 2. DOMÄNEN-Anteil (gescannt): die Domain.*-residenten Commands/Events/Trigger — der eigentliche
///    Boilerplate, der pro neuem Domain-Typ wächst. Discovery deckungsgleich mit
///    <c>EventJsonGenerator</c>/<c>WireSerializerGenerator</c> (konkrete Klassen, <c>IPipelineSelfMessage</c> aus).
///
/// Set-Gleichheit (nicht Byte-Gleichheit) zu den bisherigen Handlisten genügt: die Attribut-Reihenfolge ist
/// für STJ irrelevant. Signale (<c>StateChangeVia{Event}</c>) werden bewusst NICHT registriert — sie sind
/// uniform <c>(StreamId, Version)</c> und werden vom <c>WireSerializerGenerator</c> selbst serialisiert.
/// Drift-Schutz bleibt COMPILE-ZEIT (die Generatoren referenzieren je Typ <c>Default.{Typ}</c>).
/// </summary>
public static class JsonContextEmitter
{
    // ── FRAMEWORK-Kopf: Marten-Storage-Kontext ──────────────────────────────────────────────
    private const string EventContextHeader = """
        // <auto-generated/> — erzeugt vom Cqrs.Codegen-Prepass. NICHT von Hand ändern.
        // FRAMEWORK-Kopf (stabil) + gescannte Domänen-Events. Siehe JsonContextEmitter.
        #nullable enable
        using System.Text.Json.Serialization;
        using Infrastructure.Aggregate;
        using Infrastructure.Prozess;

        namespace Infrastructure.Serialization;

        /// <summary>
        /// STJ-Manifest über ALLE persistierbaren Events (Marten-STORAGE). Metadata-Mode: kombinierbar mit
        /// Martens JsonSerializerOptions + Resolver-Chain. Der EventJsonGenerator koppelt die Menge zur
        /// Compile-Zeit (Default.{Event}).
        /// </summary>
        [JsonSourceGenerationOptions(GenerationMode = JsonSourceGenerationMode.Metadata)]
        // ── Framework: Prozess-intern + Aggregat-Inbox (IEvent → persistiert) ──
        [JsonSerializable(typeof(ProzessGestartet))]
        [JsonSerializable(typeof(ProzessBeendet))]
        [JsonSerializable(typeof(SchrittGescheitert))]
        [JsonSerializable(typeof(KommandoVerarbeitet))]
        [JsonSerializable(typeof(KommandoAbgelehnt))]
        """;

    // ── FRAMEWORK-Kopf: Cross-Node-Wire-Kontext ─────────────────────────────────────────────
    private const string WireContextHeader = """
        // <auto-generated/> — erzeugt vom Cqrs.Codegen-Prepass. NICHT von Hand ändern.
        // FRAMEWORK-Kopf (stabil) + gescannte Domänen-Commands/Events/Trigger. Siehe JsonContextEmitter.
        #nullable enable
        using System.Text.Json.Serialization;
        using Abstractions;
        using Infrastructure.Aggregate;
        using Infrastructure.Prozess;
        using Infrastructure.Projections;
        using Infrastructure.PubSub.Messages;

        namespace Infrastructure.Serialization;

        /// <summary>
        /// STJ-Manifest für den internen Actor-Plane (WIRE): Transport-Hüllen + ALLE Commands/Events (inkl.
        /// Transient) + Trigger. Polymorphe Interface-Payloads laufen über die eingebackenen Converter.
        /// Signale sind BEWUSST nicht registriert (uniform, vom WireSerializerGenerator selbst serialisiert).
        /// Der WireSerializerGenerator koppelt die Menge zur Compile-Zeit (Default.{Typ}).
        /// </summary>
        [JsonSourceGenerationOptions(
            GenerationMode = JsonSourceGenerationMode.Metadata,
            Converters = new[]
            {
                typeof(IEventJsonConverter),
                typeof(ICommandJsonConverter),
                typeof(CommandModusJsonConverter),
                typeof(IStateChangeSignalJsonConverter),
                typeof(IMessageEnvelopeJsonConverter),
                typeof(PidJsonConverter),
            })]
        // ── Framework: Wire-Hüllen (IWireMessage) ──
        [JsonSerializable(typeof(CommandEnvelope))]
        [JsonSerializable(typeof(CommandResult))]
        [JsonSerializable(typeof(Wake))]
        [JsonSerializable(typeof(WakeAck))]
        [JsonSerializable(typeof(EventEnvelope))]
        [JsonSerializable(typeof(SignalEnvelope))]
        [JsonSerializable(typeof(Publish))]
        [JsonSerializable(typeof(Subscribe))]
        [JsonSerializable(typeof(Unsubscribe))]
        [JsonSerializable(typeof(Ack))]
        [JsonSerializable(typeof(Activate))]
        [JsonSerializable(typeof(GetSubscriberCount))]
        [JsonSerializable(typeof(SubscriberCountResponse))]
        [JsonSerializable(typeof(PipelineAck))]
        [JsonSerializable(typeof(ProzessWake))]
        // ── Framework: Ergebnis-/Prozess-/Inbox-Events (reisen im Wire) ──
        [JsonSerializable(typeof(CommandFailed))]
        [JsonSerializable(typeof(ProzessGestartet))]
        [JsonSerializable(typeof(ProzessBeendet))]
        [JsonSerializable(typeof(SchrittGescheitert))]
        [JsonSerializable(typeof(KommandoVerarbeitet))]
        [JsonSerializable(typeof(KommandoAbgelehnt))]
        """;

    public static (string EventContext, string WireContext, string Stats) Emit(
        IReadOnlyList<Assembly> domainAssemblies)
    {
        var persistableEvents = new SortedSet<string>(StringComparer.Ordinal);
        var wire = new SortedSet<string>(StringComparer.Ordinal);

        // Es werden AUSSCHLIESSLICH die drei geladenen Domain-Assemblies durchsucht
        // (assembly.GetTypes() liefert nur die dort DEFINIERTEN Typen) — deckungsgleich zum
        // domainAssemblies-Filter der Roslyn-Variante. Interface-Zugehörigkeit per FullName
        // (MetadataLoadContext-Typen sind inspection-only). Nur die konkreten Klassen zählen,
        // IPipelineSelfMessage bleibt aus, Signale werden bewusst nicht registriert.
        foreach (var asm in domainAssemblies)
        {
            foreach (var t in ConcreteClasses(asm))
            {
                var ifaces = t.GetInterfaces().Select(i => i.FullName).ToHashSet(StringComparer.Ordinal);
                if (ifaces.Contains("Abstractions.IPipelineSelfMessage"))
                    continue;

                var name = "global::" + FullyQualified(t);
                var isEvent = ifaces.Contains("Abstractions.IEvent");
                var isTransient = ifaces.Contains("Abstractions.ITransientEvent");
                var isCommand = ifaces.Contains("Abstractions.ICommand");
                var isTrigger = ifaces.Contains("Abstractions.IPipelineTrigger");
                var isWire = ifaces.Contains("Abstractions.IWireMessage");

                if (isEvent && !isTransient) persistableEvents.Add(name);
                if (isEvent || isCommand || isTrigger || isWire) wire.Add(name);
            }
        }

        var eventCtx = Build(EventContextHeader, "EventJsonSerializerContext", persistableEvents,
            "Domänen-Events (Domain.*, persistierbar)");
        var wireCtx = Build(WireContextHeader, "CqrsWireJsonContext", wire,
            "Domänen-Commands/Events/Trigger (Domain.*)");

        var stats = $"Storage-Events: {persistableEvents.Count + 5} (5 Framework), Wire-Typen: {wire.Count + 21} (21 Framework)";
        return (eventCtx, wireCtx, stats);
    }

    private static string Build(string header, string className, IEnumerable<string> domainTypes, string sectionNote)
    {
        var sb = new StringBuilder();
        sb.Append(header);
        sb.AppendLine();
        sb.AppendLine($"// ── {sectionNote} (gescannt) ──");
        foreach (var t in domainTypes)
            sb.AppendLine($"[JsonSerializable(typeof({t}))]");
        sb.AppendLine($"public partial class {className} : JsonSerializerContext");
        sb.AppendLine("{");
        sb.AppendLine("}");
        return sb.ToString();
    }

    // Konkrete Klassen (keine Structs/Enums/Interfaces, nicht abstrakt, nicht statisch).
    // Statische Klassen sind in Reflection abstract+sealed → durch !IsAbstract ausgeschlossen.
    private static IEnumerable<Type> ConcreteClasses(Assembly assembly)
    {
        Type?[] types;
        try
        {
            types = assembly.GetTypes();
        }
        catch (ReflectionTypeLoadException ex)
        {
            types = ex.Types;
        }

        foreach (var t in types)
        {
            if (t is null) continue;
            if (t.IsClass && !t.IsAbstract)
                yield return t;
        }
    }

    /// <summary>Voll namespace-qualifizierter Name mit '.'-getrennten geschachtelten Typen (ohne global::).</summary>
    private static string FullyQualified(Type t)
    {
        var name = t.Name;
        var tick = name.IndexOf('`');
        if (tick >= 0)
            name = name.Substring(0, tick);

        if (t.IsNested && t.DeclaringType != null)
            return FullyQualified(t.DeclaringType) + "." + name;

        return string.IsNullOrEmpty(t.Namespace) ? name : t.Namespace + "." + name;
    }
}
