using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Linq;

namespace Domain.SourceGeneration
{
    internal class HandlerGeneratorModel
    {
        public string Namespace { get; }
        public string StateTypeName { get; }
        public string HandlerName { get; }
        public string DeciderName { get; }
        public string ApplierName { get; }
        public List<DecideMethodInfo> DecideMethods { get; }
        public List<string> EventTypes { get; }

        public HandlerGeneratorModel(
            string ns, string stateTypeName, string handlerName,
            List<DecideMethodInfo> decideMethods, List<string> eventTypes)
        {
            Namespace = ns;
            StateTypeName = stateTypeName;
            HandlerName = handlerName;
            DeciderName = $"{stateTypeName}.Decider";
            ApplierName = $"{stateTypeName}.Applier";
            DecideMethods = decideMethods;
            EventTypes = eventTypes;
        }
    }

    /// <summary>
    /// Info Ã¼ber eine einzelne Decide-Methode.
    /// Der Generator braucht den Command-Typ UND ob ein OneOf-Unwrap nÃ¶tig ist.
    /// </summary>
    internal class DecideMethodInfo
    {
        public string CommandType { get; }
        public bool ReturnsOneOf { get; }

        public DecideMethodInfo(string commandType, bool returnsOneOf)
        {
            CommandType = commandType;
            ReturnsOneOf = returnsOneOf;
        }
    }
    
    internal static class HandlerCodeGenerationModule
    {
        public static string GenerateHandler(HandlerGeneratorModel model)
        {
            // â˜… OneOf-Migration: Decide-Methoden die OneOf returnen brauchen .Select(o => o.Value)
            var commandCases = string.Join("\n", model.DecideMethods.Select(m =>
            {
                if (m.ReturnsOneOf)
                    return $"                case {m.CommandType} cmd: return _decider.Decide(cmd).Select(o => (IEvent)o.Value);";
                else
                    return $"                case {m.CommandType} cmd: return _decider.Decide(cmd);";
            }));

            var eventCases = string.Join("\n", model.EventTypes.Select(evt =>
                $"                case {evt} e: _applier.Apply(e); break;"));

            // â˜… Braucht System.Linq fÃ¼r .Select() bei OneOf-Unwrap
            var needsLinq = model.DecideMethods.Any(m => m.ReturnsOneOf);

            return $$"""
                     // <auto-generated/>
                     #nullable enable
                     using System;
                     using System.Collections.Generic;
                     {{(needsLinq ? "using System.Linq;" : "")}}
                     using Abstractions;
                     using Core;
                     
                     namespace {{model.Namespace}}
                     {
                         public partial class {{model.HandlerName}} : AggregateHandlerBase<{{model.StateTypeName}}, {{model.DeciderName}}, {{model.ApplierName}}>
                         {
                             public {{model.HandlerName}}({{model.StateTypeName}} state, {{model.DeciderName}} decider, {{model.ApplierName}} applier)
                                 : base(state, decider, applier) { }
                     
                             public override IEnumerable<IEvent> HandleCommand(ICommand command)
                             {
                                 switch (command)
                                 {
                     {{commandCases}}
                                     default: throw new NotSupportedException($"Command type {command.GetType().Name} is not supported for {{model.StateTypeName}}.");
                                 }
                             }
                     
                             public override void ApplyEvent(IEvent @event)
                             {
                                 switch (@event)
                                 {
                     {{eventCases}}
                                     default: throw new NotSupportedException($"Event type {@event.GetType().Name} is not supported for {{model.StateTypeName}}.");
                                 }
                             }
                         }
                     }
                     """;
        }
    }

    [Generator]
    public class AggregateHandlerGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var classProvider = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (s, _) => s is ClassDeclarationSyntax,
                    transform: static (ctx, _) => GetSemanticTargetForGeneration(ctx))
                .Where(static m => m is not null);
            
            var uniqueClassProvider = classProvider.Collect()
                .SelectMany((collected, _) => collected.Distinct(SymbolEqualityComparer.Default)
                                                        .OfType<INamedTypeSymbol>());

            context.RegisterSourceOutput(uniqueClassProvider,
                static (spc, source) => Execute(spc, source));
        }

        private static INamedTypeSymbol? GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
        {
            var classDeclaration = (ClassDeclarationSyntax)context.Node;
            if (context.SemanticModel.GetDeclaredSymbol(classDeclaration) is not INamedTypeSymbol classSymbol) return null;

            var iStateSymbol = context.SemanticModel.Compilation.GetTypeByMetadataName("Abstractions.IState");
            if (iStateSymbol is null) return null;
            
            bool isStateAggregateRoot = classSymbol.AllInterfaces.Any(i => SymbolEqualityComparer.Default.Equals(i, iStateSymbol)) &&
                                        classSymbol.GetTypeMembers("Decider").Any() &&
                                        classSymbol.GetTypeMembers("Applier").Any();
            
            return isStateAggregateRoot ? classSymbol : null;
        }
       
        private static void Execute(SourceProductionContext context, INamedTypeSymbol classSymbol)
        {
            var stateTypeName = classSymbol.Name;
            var namespaceName = classSymbol.ContainingNamespace.ToDisplayString();

            var deciderSymbol = classSymbol.GetTypeMembers("Decider").FirstOrDefault();
            var applierSymbol = classSymbol.GetTypeMembers("Applier").FirstOrDefault();

            if (deciderSymbol is null || applierSymbol is null) return;
            
            // â˜… OneOf-Migration: Pro Decide-Methode analysieren ob OneOf im RÃ¼ckgabetyp steckt
            var decideMethods = GetDecideMethodInfos(deciderSymbol);
            var eventTypes = GetMethodParameterTypes(applierSymbol, "Apply");

            var model = new HandlerGeneratorModel(
                ns: namespaceName,
                stateTypeName: stateTypeName,
                handlerName: $"{stateTypeName}AggregateHandler",
                decideMethods: decideMethods,
                eventTypes: eventTypes
            );
            
            var sourceCode = HandlerCodeGenerationModule.GenerateHandler(model);

            context.AddSource($"{model.HandlerName}.g.cs", sourceCode);
        }

        /// <summary>
        /// â˜… Analysiert jede Decide-Methode: Command-Typ + ob der Return-Typ OneOf enthÃ¤lt.
        /// 
        /// IEnumerable&lt;LagerartikelErstellt&gt;                           â†’ ReturnsOneOf = false (Kovarianz reicht)
        /// IEnumerable&lt;OneOf&lt;WarenabgangGebucht, AbgangAbgelehnt&gt;&gt; â†’ ReturnsOneOf = true  (braucht .Select unwrap)
        /// </summary>
        private static List<DecideMethodInfo> GetDecideMethodInfos(INamedTypeSymbol deciderSymbol)
        {
            return deciderSymbol.GetMembers("Decide")
                .OfType<IMethodSymbol>()
                .Where(m => m.Parameters.Length == 1)
                .Select(m =>
                {
                    var commandType = m.Parameters.First().Type.ToDisplayString();
                    var returnsOneOf = IsOneOfReturnType(m.ReturnType);
                    return new DecideMethodInfo(commandType, returnsOneOf);
                })
                .ToList();
        }

        /// <summary>
        /// PrÃ¼ft ob der RÃ¼ckgabetyp IEnumerable&lt;OneOf&lt;...&gt;&gt; ist.
        /// </summary>
        private static bool IsOneOfReturnType(ITypeSymbol returnType)
        {
            if (returnType is INamedTypeSymbol { IsGenericType: true } enumerable
                && enumerable.OriginalDefinition.ToDisplayString()
                    .StartsWith("System.Collections.Generic.IEnumerable"))
            {
                var elementType = enumerable.TypeArguments[0];
                return elementType is INamedTypeSymbol { Name: "OneOf" };
            }
            return false;
        }

        private static List<string> GetMethodParameterTypes(INamedTypeSymbol typeSymbol, string methodName)
        {
            return typeSymbol.GetMembers(methodName)
                .OfType<IMethodSymbol>()
                .Where(m => m.Parameters.Length == 1)
                .Select(m => m.Parameters.First().Type.ToDisplayString())
                .Distinct()
                .ToList();
        }
    }
}