using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;

namespace Domain.SourceGeneration
{
    internal class FactoryGeneratorModel
    {
        public string FactoryNamespace { get; }
        public string FactoryClassName { get; }
        public List<AggregateInfo> Aggregates { get; }

        public FactoryGeneratorModel(string factoryNamespace, string factoryClassName, List<AggregateInfo> aggregates)
        {
            FactoryNamespace = factoryNamespace;
            FactoryClassName = factoryClassName;
            Aggregates = aggregates;
        }
    }

    internal class AggregateInfo
    {
        public string StateTypeName { get; }
        public string StateTypeParameterName { get; }
        public string HandlerTypeName { get; }
        public string StateNamespace { get; }

        public AggregateInfo(string stateTypeName)
        {
            StateTypeName = stateTypeName;
            var parts = stateTypeName.Split('.');
            var name = parts.Last();
            StateTypeParameterName = $"{name.Substring(0, 1).ToLower()}{name.Substring(1)}State";
            HandlerTypeName = $"{stateTypeName}AggregateHandler";
            StateNamespace = stateTypeName.Substring(0, stateTypeName.LastIndexOf('.'));
        }
    }
    
    internal static class FactoryCodeGenerationModule
    {
        public static string GenerateFactory(FactoryGeneratorModel model)
        {
            var usingDirectives = string.Join("\n", model.Aggregates.Select(a => a.StateNamespace).Distinct().Select(ns => $"using {ns};"));
            
            var caseBlocks = string.Join("\n", model.Aggregates.Select(agg =>
                $$"""
                        case {{agg.StateTypeName}} {{agg.StateTypeParameterName}}:
                        {
                            var decider = new {{agg.StateTypeName}}.Decider({{agg.StateTypeParameterName}});
                            var applier = new {{agg.StateTypeName}}.Applier({{agg.StateTypeParameterName}});
                            return new {{agg.HandlerTypeName}}({{agg.StateTypeParameterName}}, decider, applier);
                        }
                """));

            return $$"""
                       // <auto-generated/>
                       #nullable enable
                       using System;
                       using Abstractions;
                       {{usingDirectives}}
                       
                       namespace {{model.FactoryNamespace}}
                       {
                           public class {{model.FactoryClassName}} : IAggregateHandlerFactory
                           {
                               public IAggregateHandler CreateHandler(IState state)
                               {
                                   switch (state)
                                   {
                       {{caseBlocks}}
                                       default:
                                           throw new NotSupportedException($"No handler configured for aggregate type {state.GetType().Name}.");
                                   }
                               }
                           }
                       }
                       """;
        }
    }

    [Generator]
    public class HandlerFactoryGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var aggregateRootsProvider = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (s, _) => s is ClassDeclarationSyntax,
                    transform: static (ctx, _) => GetSemanticTargetForGeneration(ctx))
                .Where(static m => m is not null);

            var collectedAggregates = aggregateRootsProvider.Collect();

            context.RegisterSourceOutput(collectedAggregates,
                static (spc, source) => Execute(spc, source));
        }

        private static INamedTypeSymbol? GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
        {
            var classDeclaration = (ClassDeclarationSyntax)context.Node;
            if (context.SemanticModel.GetDeclaredSymbol(classDeclaration) is not INamedTypeSymbol classSymbol) return null;

            var iStateSymbol = context.SemanticModel.Compilation.GetTypeByMetadataName("Abstractions.IState");
            if (iStateSymbol is null) return null;

            bool isStateAggregateRoot = classSymbol.AllInterfaces.Any(i => SymbolEqualityComparer.Default.Equals(i, iStateSymbol)) &&
                                        classSymbol.GetTypeMembers("Decider").Any() &&
                                        classSymbol.GetTypeMembers("Applier").Any();

            return isStateAggregateRoot ? classSymbol : null;
        }

        private static void Execute(SourceProductionContext context, ImmutableArray<INamedTypeSymbol?> aggregates)
        {
            if (aggregates.IsDefaultOrEmpty) return;

            var distinctAggregates = aggregates.OfType<INamedTypeSymbol>()
                .Distinct(SymbolEqualityComparer.Default)
                .Select(s => new AggregateInfo(s.ToDisplayString()))
                .ToList();

            if (!distinctAggregates.Any()) return;
            
            var model = new FactoryGeneratorModel(
                factoryNamespace: "Infrastructure",
                factoryClassName: "AggregateHandlerFactory",
                aggregates: distinctAggregates
            );

            var sourceCode = FactoryCodeGenerationModule.GenerateFactory(model);
            context.AddSource("AggregateHandlerFactory.g.cs", sourceCode);
        }
    }
}