using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Domain.SourceGeneration
{
    internal class SimpleGeneratorModel
    {
        public string Namespace { get; }
        public string StateTypeName { get; }
        public string HandlerClassName { get; }

        public SimpleGeneratorModel(string ns, string stateTypeName, string handlerClassName)
        {
            Namespace = ns;
            StateTypeName = stateTypeName;
            HandlerClassName = handlerClassName;
        }
    }


    internal static class CodeGenerationModules
    {
        public static string GeneratePartialHandlerClass(SimpleGeneratorModel model)
        {
            return $$"""
                     // <auto-generated/>
                     // do net change!
                     #nullable enable

                     namespace {{model.Namespace}};

                     public partial class {{model.StateTypeName}}
                     {
                         public partial class {{model.HandlerClassName}}
                         {
                             private {{model.StateTypeName}} State { get; }

                             public {{model.HandlerClassName}}({{model.StateTypeName}} state)
                             {
                                 this.State = state;
                             }
                         }
                     }
                     """;
        }
    }


   [Generator]
    public class Generator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var classDeclarations = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (s, _) => IsSyntaxTargetForGeneration(s),
                    transform: static (ctx, _) => GetSemanticTargetForGeneration(ctx))
                .Where(static m => m is not null);

            context.RegisterSourceOutput(classDeclarations,
                static (spc, source) => Execute(spc, source!));
        }

        private static bool IsSyntaxTargetForGeneration(SyntaxNode node)
        {
            return node is ClassDeclarationSyntax c && c.Modifiers.Any(m => m.ValueText == "partial") &&
                   c.BaseList != null;
        }

        private static INamedTypeSymbol? GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
        {
            var classDeclaration = (ClassDeclarationSyntax)context.Node;
            if (context.SemanticModel.GetDeclaredSymbol(classDeclaration) is not INamedTypeSymbol classSymbol)
                return null;

            var deciderInterfaceSymbol =
                context.SemanticModel.Compilation.GetTypeByMetadataName("Abstractions.IDecider`1");
            var applierInterfaceSymbol =
                context.SemanticModel.Compilation.GetTypeByMetadataName("Abstractions.IApplier`1");

            // ★ IReader ausgeschlossen — Reader sind jetzt Top-Level-Klassen mit eigenem DI.
            //   Nur Decider und Applier (Inner Classes) brauchen generierte State-Property.

            if (deciderInterfaceSymbol is null && applierInterfaceSymbol is null)
                return null;

            foreach (var implementedInterface in classSymbol.AllInterfaces)
            {
                var originalInterface = implementedInterface.OriginalDefinition;
                if ((deciderInterfaceSymbol != null && SymbolEqualityComparer.Default.Equals(originalInterface, deciderInterfaceSymbol)) ||
                    (applierInterfaceSymbol != null && SymbolEqualityComparer.Default.Equals(originalInterface, applierInterfaceSymbol)))
                {
                    return classSymbol;
                }
            }

            return null;
        }

        private static void Execute(SourceProductionContext context, INamedTypeSymbol classSymbol)
        {
            if (classSymbol.ContainingType is null)
                return;

            var className = classSymbol.Name;
            var stateType = classSymbol.ContainingType.Name;
            var namespaceName = classSymbol.ContainingNamespace.ToDisplayString();

            var model = new SimpleGeneratorModel(
                ns: namespaceName,
                stateTypeName: stateType,
                handlerClassName: className
            );

            var sourceCode = CodeGenerationModules.GeneratePartialHandlerClass(model);
            context.AddSource($"{stateType}.{className}.State.g.cs", sourceCode);
        }
    }
}