using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Domain.SourceGeneration;

/// <summary>
/// Generiert für jeden Reader (IReader&lt;TProjection&gt;):
/// - SupportedQueryTypes (statische Liste)
/// - DispatchAsync (Query-Routing mit Envelope + ReadContext)
///
/// Erkennung: Top-Level-Klassen die IReader&lt;T&gt; implementieren.
/// Handle-Signatur: (TQuery, IMessageEnvelope, ReadContext)
/// Return-Typ-Analyse: Task&lt;OneOf&lt;...&gt;&gt; → unwrap .Value, Task&lt;T&gt; → direkt
/// </summary>
[Generator]
public class ProjectionReaderDispatchGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var readerProvider = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is ClassDeclarationSyntax c &&
                                            c.Modifiers.Any(m => m.Text == "partial") &&
                                            c.BaseList != null,
                transform: static (ctx, _) => GetReaderInfo(ctx))
            .Where(static m => m is not null);

        context.RegisterSourceOutput(readerProvider,
            static (spc, readerInfo) => Execute(spc, readerInfo!));
    }

    private static ReaderGeneratorModel? GetReaderInfo(GeneratorSyntaxContext context)
    {
        var classDecl = (ClassDeclarationSyntax)context.Node;
        var classSymbol = context.SemanticModel.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;

        if (classSymbol == null)
            return null;

        var readerInterfaceDef = context.SemanticModel.Compilation
            .GetTypeByMetadataName("Abstractions.IReader`1");

        if (readerInterfaceDef == null)
            return null;

        var readerInterface = classSymbol.AllInterfaces
            .FirstOrDefault(i => i.OriginalDefinition.Equals(readerInterfaceDef, SymbolEqualityComparer.Default));

        if (readerInterface == null)
            return null;

        var projectionType = readerInterface.TypeArguments[0];

        var messageEnvelopeType = context.SemanticModel.Compilation
            .GetTypeByMetadataName("Abstractions.IMessageEnvelope");
        var readContextType = context.SemanticModel.Compilation
            .GetTypeByMetadataName("Abstractions.ReadContext");

        if (messageEnvelopeType == null || readContextType == null)
            return null;

        // Handle-Methoden: (TQuery, IMessageEnvelope, ReadContext)
        var handleMethods = classSymbol.GetMembers("Handle")
            .OfType<IMethodSymbol>()
            .Where(m => m.Parameters.Length == 3 &&
                        SymbolEqualityComparer.Default.Equals(
                            m.Parameters[1].Type, messageEnvelopeType) &&
                        SymbolEqualityComparer.Default.Equals(
                            m.Parameters[2].Type, readContextType))
            .ToList();

        if (handleMethods.Count == 0)
            return null;

        var handlers = new List<ReaderHandlerInfo>();
        foreach (var method in handleMethods)
        {
            var queryTypeName = method.Parameters[0].Type.ToDisplayString();
            var kind = AnalyzeReturnType(method.ReturnType);
            handlers.Add(new ReaderHandlerInfo(queryTypeName, kind));
        }

        return new ReaderGeneratorModel(
            readerNamespace: classSymbol.ContainingNamespace.ToDisplayString(),
            readerName: classSymbol.Name,
            projectionName: projectionType.Name,
            handlers: handlers
        );
    }

    private static ReaderHandlerKind AnalyzeReturnType(ITypeSymbol returnType)
    {
        if (returnType is INamedTypeSymbol { IsGenericType: true, Name: "Task" } taskType)
        {
            var innerType = taskType.TypeArguments[0];
            if (innerType is INamedTypeSymbol { Name: "OneOf", IsGenericType: true })
                return ReaderHandlerKind.TaskOneOf;
        }
        return ReaderHandlerKind.TaskDirect;
    }

    private static void Execute(SourceProductionContext context, ReaderGeneratorModel model)
    {
        var source = GenerateReaderDispatch(model);
        context.AddSource($"{model.ReaderName}.Dispatch.g.cs", source);
    }

    private static string GenerateReaderDispatch(ReaderGeneratorModel model)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Abstractions;");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.ReaderNamespace};");
        sb.AppendLine();
        sb.AppendLine($"public partial class {model.ReaderName}");
        sb.AppendLine("{");

        // ── SupportedQueryTypes ──
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Query-Typen die dieser Reader verarbeiten kann.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static IReadOnlyList<Type> SupportedQueryTypes { get; } = new[]");
        sb.AppendLine("    {");
        foreach (var handler in model.Handlers)
        {
            var simpleType = GetSimpleTypeName(handler.QueryTypeName);
            sb.AppendLine($"        typeof({simpleType}),");
        }
        sb.AppendLine("    };");
        sb.AppendLine();

        // ── DispatchAsync ──
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Routet eine Query an die passende Handle-Methode.");
        sb.AppendLine("    /// OneOf-Returns werden zu IQueryResponse unwrappt.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public async Task<IQueryResponse> DispatchAsync(IQuery query, IMessageEnvelope envelope, ReadContext ctx)");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (query)");
        sb.AppendLine("        {");

        foreach (var handler in model.Handlers)
        {
            var simpleType = GetSimpleTypeName(handler.QueryTypeName);

            switch (handler.Kind)
            {
                case ReaderHandlerKind.TaskOneOf:
                    sb.AppendLine($"            case {simpleType} q:");
                    sb.AppendLine($"                var r_{simpleType} = await Handle(q, envelope, ctx);");
                    sb.AppendLine($"                return (IQueryResponse)r_{simpleType}.Value;");
                    break;

                case ReaderHandlerKind.TaskDirect:
                    sb.AppendLine($"            case {simpleType} q:");
                    sb.AppendLine($"                return await Handle(q, envelope, ctx);");
                    break;
            }
        }

        sb.AppendLine($"            default:");
        sb.AppendLine($"                throw new NotSupportedException($\"Query type {{query.GetType().Name}} is not supported by {model.ReaderName}.\");");
        sb.AppendLine("        }");
        sb.AppendLine("    }");

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string GetSimpleTypeName(string fullName)
    {
        var lastDot = fullName.LastIndexOf('.');
        return lastDot >= 0 ? fullName.Substring(lastDot + 1) : fullName;
    }
}

// ═══════════════════════════════════════════════════════════
// Modelle
// ═══════════════════════════════════════════════════════════

internal enum ReaderHandlerKind
{
    TaskOneOf,
    TaskDirect,
}

internal class ReaderHandlerInfo
{
    public string QueryTypeName { get; }
    public ReaderHandlerKind Kind { get; }

    public ReaderHandlerInfo(string queryTypeName, ReaderHandlerKind kind)
    {
        QueryTypeName = queryTypeName;
        Kind = kind;
    }
}

internal class ReaderGeneratorModel
{
    public string ReaderNamespace { get; }
    public string ReaderName { get; }
    public string ProjectionName { get; }
    public List<ReaderHandlerInfo> Handlers { get; }

    public ReaderGeneratorModel(
        string readerNamespace,
        string readerName,
        string projectionName,
        List<ReaderHandlerInfo> handlers)
    {
        ReaderNamespace = readerNamespace;
        ReaderName = readerName;
        ProjectionName = projectionName;
        Handlers = handlers;
    }
}