using Microsoft.CodeAnalysis;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Domain.SourceGeneration
{
    /// <summary>
    /// Der EINE Prozess-Generator im neuen Modell (Spec §4): er emittiert aus jeder
    /// <c>IProzessDefinition</c> den DAG-DESKRIPTOR — die Regeln als Daten — in eine Registry
    /// <c>GeneratedProzessRegeln.Alle</c> (Prozess-Name → <c>ProzessRegeln</c>). KEIN per-Prozess-Aggregat
    /// mehr: der Manager ist generisch, die Regeln parameterisieren ihn. Der Prozess-Name ist der
    /// Definitions-Klassenname (daraus leitet der Korrelations-Router die Korrelation ab).
    ///
    /// Die Infrastruktur-Seite (Manager-Kind, Router, Startup) ist generisch und handgeschrieben — sie
    /// liest nur diese Registry. Deshalb genügt EIN Domain-Generator; kein Infrastructure-Generator nötig.
    /// </summary>
    [Generator]
    public class ProzessRegelnGenerator : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context) { }

        public void Execute(GeneratorExecutionContext context)
        {
            var comp = context.Compilation;
            var iDef = comp.GetTypeByMetadataName("Abstractions.IProzessDefinition");
            if (iDef == null) return;

            var declared = new List<INamedTypeSymbol>();
            Collect(comp.GlobalNamespace, comp.Assembly, declared);

            var defs = declared
                .Where(t => t.TypeKind == TypeKind.Class && !t.IsAbstract &&
                            t.AllInterfaces.Contains(iDef, SymbolEqualityComparer.Default))
                .OrderBy(t => t.Name)
                .ToList();

            // Nur die Assembly emittiert die Registry, die auch Definitionen deklariert (Domain). Sonst
            // entstünden in Domain.Pipeline/Domain.Projections leere Doppel-Klassen → CS0433-Kollision.
            if (defs.Count == 0) return;

            context.AddSource("GeneratedProzessRegeln.g.cs", Emit(defs));
        }

        private static void Collect(INamespaceSymbol ns, IAssemblySymbol assembly, List<INamedTypeSymbol> acc)
        {
            foreach (var t in ns.GetTypeMembers())
                if (SymbolEqualityComparer.Default.Equals(t.ContainingAssembly, assembly))
                    acc.Add(t);
            foreach (var child in ns.GetNamespaceMembers())
                Collect(child, assembly, acc);
        }

        private static string Emit(List<INamedTypeSymbol> defs)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// Regel-Registry pro IProzessDefinition (ProzessRegelnGenerator). Nicht editieren.");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using Abstractions;");
            sb.AppendLine();
            sb.AppendLine("namespace Domain.Prozess");
            sb.AppendLine("{");
            sb.AppendLine("    public static class GeneratedProzessRegeln");
            sb.AppendLine("    {");
            sb.AppendLine("        // Prozess-Name (= Definitions-Klassenname) → seine Regeln (der DAG-Deskriptor).");
            sb.AppendLine("        public static readonly IReadOnlyDictionary<string, ProzessRegeln> Alle =");
            sb.AppendLine("            new Dictionary<string, ProzessRegeln>");
            sb.AppendLine("        {");
            foreach (var d in defs)
                sb.AppendLine($"            [\"{d.Name}\"] = new {d.ToDisplayString()}().Regeln,");
            sb.AppendLine("        };");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }
    }
}
