using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Domain.SourceGeneration
{
    /// <summary>
    /// Generiert pro PERSISTIERTEM Event-Typ ein Signal `StateChangeVia{Event}` (Spec 4.3 / 5.1).
    ///
    /// Ein Signal trägt nur `(StreamId, Version)` — ein Weckruf, keine Nutzlast. Es
    /// implementiert IStateChangeSignal (→ IMessagePayload), läuft also durch dasselbe
    /// typ-geshardete PubSub wie Events; Reihenfolge/Exactly-once kommen aber NICHT vom
    /// Signal, sondern aus dem Log-Read des Adapters (Phase 2).
    ///
    /// WARUM syntax-basiert (nur die im aktuellen Projekt DEKLARIERTEN Events): So
    /// entsteht pro Event genau EIN Signal, co-lokalisiert im selben Namespace/Assembly.
    /// Eine compilation-weite Erkennung würde referenzierte Events doppelt sehen und
    /// denselben Signal-Typ in mehreren Assemblies erzeugen (Konflikt).
    ///
    /// AUSGESCHLOSSEN: ITransientEvent — die stehen nicht im Log, es gibt nichts
    /// nachzulesen, also kein Signal (Spec: „pro persistiertem Event-Typ").
    /// </summary>
    [Generator]
    public class SignalTypeGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var signals = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (s, _) => IsCandidate(s),
                    transform: static (ctx, _) => GetSignalModel(ctx))
                .Where(static m => m is not null);

            context.RegisterSourceOutput(signals,
                static (spc, model) => Execute(spc, model!));
        }

        private static bool IsCandidate(SyntaxNode node)
            => node is TypeDeclarationSyntax t
               && (t is RecordDeclarationSyntax || t is ClassDeclarationSyntax)
               && t.BaseList != null;

        private static SignalModel? GetSignalModel(GeneratorSyntaxContext context)
        {
            var decl = (TypeDeclarationSyntax)context.Node;
            if (context.SemanticModel.GetDeclaredSymbol(decl) is not INamedTypeSymbol symbol)
                return null;

            var iEvent = context.SemanticModel.Compilation
                .GetTypeByMetadataName("Abstractions.IEvent");
            if (iEvent is null)
                return null;

            var iTransient = context.SemanticModel.Compilation
                .GetTypeByMetadataName("Abstractions.ITransientEvent");

            var interfaces = symbol.AllInterfaces;
            var isEvent = interfaces.Contains(iEvent, SymbolEqualityComparer.Default);
            var isTransient = iTransient != null
                && interfaces.Contains(iTransient, SymbolEqualityComparer.Default);

            if (!isEvent || isTransient)
                return null;

            return new SignalModel(
                symbol.ContainingNamespace.ToDisplayString(),
                symbol.Name);
        }

        private static void Execute(SourceProductionContext context, SignalModel model)
        {
            var source = $$"""
                // <auto-generated/>
                #nullable enable
                using Abstractions;

                namespace {{model.Namespace}};

                /// <summary>
                /// Signal (Weckruf) für {{model.EventName}} — trägt nur (StreamId, Version).
                /// Generiert vom SignalTypeGenerator (Spec 5.1). Keine Nutzlast.
                /// ★ P1b (TG-1): implementiert IStateChangeSignal&lt;{{model.EventName}}&gt; → die Event→Signal-Kante
                /// steckt im Typ-Argument, nicht im Namen (der SignalFactoryGenerator liest sie typ-getrieben).
                /// </summary>
                public sealed record StateChangeVia{{model.EventName}}(
                    System.Guid StreamId, int Version) : IStateChangeSignal<global::{{model.Namespace}}.{{model.EventName}}>;
                """;

            context.AddSource($"StateChangeVia{model.EventName}.g.cs", source);
        }

        /// <summary>
        /// Modell für die Codegen. Reine Klasse (kein record) — Generatoren zielen auf
        /// netstandard2.0, wo `init`/records ohne IsExternalInit-Polyfill nicht kompilieren.
        /// </summary>
        private sealed class SignalModel
        {
            public string Namespace { get; }
            public string EventName { get; }

            public SignalModel(string ns, string eventName)
            {
                Namespace = ns;
                EventName = eventName;
            }
        }
    }
}
