using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Linq;

namespace Domain.SourceGeneration
{
    // A simple data model to pass information to the template
    internal class StateGeneratorModel
    {
        public string Namespace { get; }
        public string ClassName { get; }

        public StateGeneratorModel(string ns, string className)
        {
            Namespace = ns;
            ClassName = className;
        }
    }

    // The module containing the code template
    internal static class StateCodeGenerationModule
    {
        public static string GenerateStateProperties(StateGeneratorModel model)
        {
            return $$"""
                     // <auto-generated/>
                     #nullable enable
                     using System;
                     
                     namespace {{model.Namespace}};
                     
                     public partial class {{model.ClassName}}
                     {
                         public Guid Id { get; set; }
                         public int Version { get; set; }
                     }
                     """;
        }
    }

    [Generator]
    public class StatePropertyGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var classDeclarations = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (s, _) => s is ClassDeclarationSyntax { BaseList: not null },
                    transform: static (ctx, _) => GetSemanticTargetForGeneration(ctx))
                .Where(static m => m is not null);

            context.RegisterSourceOutput(classDeclarations,
                static (spc, source) => Execute(spc, source!));
        }

        private static INamedTypeSymbol? GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
        {
            var classDeclaration = (ClassDeclarationSyntax)context.Node;
            if (context.SemanticModel.GetDeclaredSymbol(classDeclaration) is not INamedTypeSymbol classSymbol)
            {
                return null;
            }

            var iStateInterfaceSymbol = context.SemanticModel.Compilation.GetTypeByMetadataName("Abstractions.IState");
            if (iStateInterfaceSymbol is null)
            {
                return null;
            }

            if (classSymbol.AllInterfaces.Any(i => SymbolEqualityComparer.Default.Equals(i, iStateInterfaceSymbol)))
            {
                // Ensure it's a partial class before returning
                if(classDeclaration.Modifiers.Any(m => m.ValueText == "partial"))
                {
                    return classSymbol;
                }
            }

            return null;
        }
       
        private static void Execute(SourceProductionContext context, INamedTypeSymbol classSymbol)
        {
            var model = new StateGeneratorModel(
                ns: classSymbol.ContainingNamespace.ToDisplayString(),
                className: classSymbol.Name
            );

            var sourceCode = StateCodeGenerationModule.GenerateStateProperties(model);
            context.AddSource($"{model.ClassName}.State.g.cs", sourceCode);
        }
    }
}