using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Client.SourceGeneration;

/// <summary>
/// Generiert DI-Registrierungen für alle IUiModule-Implementierungen.
///
/// Output-Pattern:
///   Namespace:  Microsoft.Extensions.DependencyInjection (immer gleich)
///   Klasse:     GeneratedModuleRegistry_{AssemblyName}
///   Methode:    AddModules_{AssemblyName}(this IServiceCollection)
///
/// Assembly-Name im Klassen- UND Methodennamen garantiert:
///   - Kein Typ-Konflikt (verschiedene Klassennamen)
///   - Kein CS0121 (verschiedene Methodennamen)
///   - Extension-Method-Syntax bleibt erhalten
///   - Kein Namespace-Import nötig (Microsoft.Extensions.DependencyInjection ist Standard)
/// </summary>
[Generator]
public class ModuleRegistryGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var modules = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is ClassDeclarationSyntax c && c.BaseList != null,
                transform: static (ctx, _) => Analyze(ctx))
            .Where(static m => m is not null);

        var assemblyName = context.CompilationProvider
            .Select(static (c, _) => c.AssemblyName ?? "Unknown");

        var combined = modules.Collect().Combine(assemblyName);

        context.RegisterSourceOutput(combined, static (spc, data) =>
        {
            var (source, asmName) = data;
            var infos = source
                .Where(x => x.HasValue)
                .Select(x => x!.Value)
                .GroupBy(x => x.Fqn)
                .Select(g => g.First())
                .OrderBy(x => x.Fqn)
                .ToList();
            Generate(spc, infos, asmName);
        });
    }

    private static (string Fqn, string Ns)? Analyze(GeneratorSyntaxContext ctx)
    {
        var symbol = ctx.SemanticModel.GetDeclaredSymbol(ctx.Node) as INamedTypeSymbol;
        if (symbol == null || symbol.IsAbstract) return null;

        var iUiModule = ctx.SemanticModel.Compilation
            .GetTypeByMetadataName("Client.Infrastructure.Abstractions.IUiModule");
        if (iUiModule == null) return null;

        if (!symbol.AllInterfaces.Any(i => SymbolEqualityComparer.Default.Equals(i, iUiModule)))
            return null;

        return (symbol.ToDisplayString(), symbol.ContainingNamespace.ToDisplayString());
    }

    private static void Generate(SourceProductionContext ctx,
        System.Collections.Generic.List<(string Fqn, string Ns)> modules,
        string assemblyName)
    {
        var suffix = Sanitize(assemblyName);
        var className = $"GeneratedModuleRegistry_{suffix}";
        var methodName = $"AddModules_{suffix}";

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Client.Infrastructure.Abstractions;");
        foreach (var ns in modules.Select(m => m.Ns).Distinct().OrderBy(n => n))
            sb.AppendLine($"using {ns};");
        sb.AppendLine();
        sb.AppendLine("namespace Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine($"public static class {className}");
        sb.AppendLine("{");
        sb.AppendLine($"    public static IServiceCollection {methodName}(this IServiceCollection services)");
        sb.AppendLine("    {");
        foreach (var m in modules)
            sb.AppendLine($"        services.AddScoped<IUiModule, {m.Fqn}>();");
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        ctx.AddSource("GeneratedModuleRegistry.g.cs", sb.ToString());
    }

    private static string Sanitize(string name)
        => new string(name.Select(c => char.IsLetterOrDigit(c) ? c : '_').ToArray());
}